// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package github

import (
	"context"
	"io"

	"github.com/google/go-github/v80/github"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitHubClient creates a new instance of MockGitHubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitHubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitHubClient {
	mock := &MockGitHubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitHubClient is an autogenerated mock type for the GitHubClient type
type MockGitHubClient struct {
	mock.Mock
}

type MockGitHubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitHubClient) EXPECT() *MockGitHubClient_Expecter {
	return &MockGitHubClient_Expecter{mock: &_m.Mock}
}

// AddLabelsToPullRequest provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) AddLabelsToPullRequest(ctx context.Context, owner string, repo string, number int, labels []string) error {
	ret := _mock.Called(ctx, owner, repo, number, labels)

	if len(ret) == 0 {
		panic("no return value specified for AddLabelsToPullRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, []string) error); ok {
		r0 = returnFunc(ctx, owner, repo, number, labels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitHubClient_AddLabelsToPullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabelsToPullRequest'
type MockGitHubClient_AddLabelsToPullRequest_Call struct {
	*mock.Call
}

// AddLabelsToPullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - labels []string
func (_e *MockGitHubClient_Expecter) AddLabelsToPullRequest(ctx interface{}, owner interface{}, repo interface{}, number interface{}, labels interface{}) *MockGitHubClient_AddLabelsToPullRequest_Call {
	return &MockGitHubClient_AddLabelsToPullRequest_Call{Call: _e.mock.On("AddLabelsToPullRequest", ctx, owner, repo, number, labels)}
}

func (_c *MockGitHubClient_AddLabelsToPullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, number int, labels []string)) *MockGitHubClient_AddLabelsToPullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitHubClient_AddLabelsToPullRequest_Call) Return(err error) *MockGitHubClient_AddLabelsToPullRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitHubClient_AddLabelsToPullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int, labels []string) error) *MockGitHubClient_AddLabelsToPullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePullRequest provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) CreatePullRequest(ctx context.Context, owner string, repo string, pull *github.NewPullRequest) (*github.PullRequest, error) {
	ret := _mock.Called(ctx, owner, repo, pull)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 *github.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.NewPullRequest) (*github.PullRequest, error)); ok {
		return returnFunc(ctx, owner, repo, pull)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *github.NewPullRequest) *github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, pull)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *github.NewPullRequest) error); ok {
		r1 = returnFunc(ctx, owner, repo, pull)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockGitHubClient_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - pull *github.NewPullRequest
func (_e *MockGitHubClient_Expecter) CreatePullRequest(ctx interface{}, owner interface{}, repo interface{}, pull interface{}) *MockGitHubClient_CreatePullRequest_Call {
	return &MockGitHubClient_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", ctx, owner, repo, pull)}
}

func (_c *MockGitHubClient_CreatePullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, pull *github.NewPullRequest)) *MockGitHubClient_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *github.NewPullRequest
		if args[3] != nil {
			arg3 = args[3].(*github.NewPullRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitHubClient_CreatePullRequest_Call) Return(pullRequest *github.PullRequest, err error) *MockGitHubClient_CreatePullRequest_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockGitHubClient_CreatePullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, pull *github.NewPullRequest) (*github.PullRequest, error)) *MockGitHubClient_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRepo provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) CreateRepo(ctx context.Context, owner string, slug string) (*github.Repository, error) {
	ret := _mock.Called(ctx, owner, slug)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepo")
	}

	var r0 *github.Repository
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*github.Repository, error)); ok {
		return returnFunc(ctx, owner, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *github.Repository); ok {
		r0 = returnFunc(ctx, owner, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_CreateRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepo'
type MockGitHubClient_CreateRepo_Call struct {
	*mock.Call
}

// CreateRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - slug string
func (_e *MockGitHubClient_Expecter) CreateRepo(ctx interface{}, owner interface{}, slug interface{}) *MockGitHubClient_CreateRepo_Call {
	return &MockGitHubClient_CreateRepo_Call{Call: _e.mock.On("CreateRepo", ctx, owner, slug)}
}

func (_c *MockGitHubClient_CreateRepo_Call) Run(run func(ctx context.Context, owner string, slug string)) *MockGitHubClient_CreateRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitHubClient_CreateRepo_Call) Return(repository *github.Repository, err error) *MockGitHubClient_CreateRepo_Call {
	_c.Call.Return(repository, err)
	return _c
}

func (_c *MockGitHubClient_CreateRepo_Call) RunAndReturn(run func(ctx context.Context, owner string, slug string) (*github.Repository, error)) *MockGitHubClient_CreateRepo_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadAsset provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) DownloadAsset(ctx context.Context, owner string, repo string, assetID int64) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, owner, repo, assetID)

	if len(ret) == 0 {
		panic("no return value specified for DownloadAsset")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, owner, repo, assetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) io.ReadCloser); ok {
		r0 = returnFunc(ctx, owner, repo, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, owner, repo, assetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_DownloadAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAsset'
type MockGitHubClient_DownloadAsset_Call struct {
	*mock.Call
}

// DownloadAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - assetID int64
func (_e *MockGitHubClient_Expecter) DownloadAsset(ctx interface{}, owner interface{}, repo interface{}, assetID interface{}) *MockGitHubClient_DownloadAsset_Call {
	return &MockGitHubClient_DownloadAsset_Call{Call: _e.mock.On("DownloadAsset", ctx, owner, repo, assetID)}
}

func (_c *MockGitHubClient_DownloadAsset_Call) Run(run func(ctx context.Context, owner string, repo string, assetID int64)) *MockGitHubClient_DownloadAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitHubClient_DownloadAsset_Call) Return(readCloser io.ReadCloser, err error) *MockGitHubClient_DownloadAsset_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockGitHubClient_DownloadAsset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, assetID int64) (io.ReadCloser, error)) *MockGitHubClient_DownloadAsset_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadAssetTo provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) DownloadAssetTo(ctx context.Context, fs afero.Fs, owner string, repo string, assetID int64, filePath string) error {
	ret := _mock.Called(ctx, fs, owner, repo, assetID, filePath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadAssetTo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, afero.Fs, string, string, int64, string) error); ok {
		r0 = returnFunc(ctx, fs, owner, repo, assetID, filePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitHubClient_DownloadAssetTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAssetTo'
type MockGitHubClient_DownloadAssetTo_Call struct {
	*mock.Call
}

// DownloadAssetTo is a helper method to define mock.On call
//   - ctx context.Context
//   - fs afero.Fs
//   - owner string
//   - repo string
//   - assetID int64
//   - filePath string
func (_e *MockGitHubClient_Expecter) DownloadAssetTo(ctx interface{}, fs interface{}, owner interface{}, repo interface{}, assetID interface{}, filePath interface{}) *MockGitHubClient_DownloadAssetTo_Call {
	return &MockGitHubClient_DownloadAssetTo_Call{Call: _e.mock.On("DownloadAssetTo", ctx, fs, owner, repo, assetID, filePath)}
}

func (_c *MockGitHubClient_DownloadAssetTo_Call) Run(run func(ctx context.Context, fs afero.Fs, owner string, repo string, assetID int64, filePath string)) *MockGitHubClient_DownloadAssetTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 afero.Fs
		if args[1] != nil {
			arg1 = args[1].(afero.Fs)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockGitHubClient_DownloadAssetTo_Call) Return(err error) *MockGitHubClient_DownloadAssetTo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitHubClient_DownloadAssetTo_Call) RunAndReturn(run func(ctx context.Context, fs afero.Fs, owner string, repo string, assetID int64, filePath string) error) *MockGitHubClient_DownloadAssetTo_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetClient() *github.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *github.Client
	if returnFunc, ok := ret.Get(0).(func() *github.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Client)
		}
	}
	return r0
}

// MockGitHubClient_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockGitHubClient_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
func (_e *MockGitHubClient_Expecter) GetClient() *MockGitHubClient_GetClient_Call {
	return &MockGitHubClient_GetClient_Call{Call: _e.mock.On("GetClient")}
}

func (_c *MockGitHubClient_GetClient_Call) Run(run func()) *MockGitHubClient_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGitHubClient_GetClient_Call) Return(client *github.Client) *MockGitHubClient_GetClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockGitHubClient_GetClient_Call) RunAndReturn(run func() *github.Client) *MockGitHubClient_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileContents provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetFileContents(ctx context.Context, owner string, repo string, path string, ref string) (string, error) {
	ret := _mock.Called(ctx, owner, repo, path, ref)

	if len(ret) == 0 {
		panic("no return value specified for GetFileContents")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (string, error)); ok {
		return returnFunc(ctx, owner, repo, path, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) string); ok {
		r0 = returnFunc(ctx, owner, repo, path, ref)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, path, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_GetFileContents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileContents'
type MockGitHubClient_GetFileContents_Call struct {
	*mock.Call
}

// GetFileContents is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - path string
//   - ref string
func (_e *MockGitHubClient_Expecter) GetFileContents(ctx interface{}, owner interface{}, repo interface{}, path interface{}, ref interface{}) *MockGitHubClient_GetFileContents_Call {
	return &MockGitHubClient_GetFileContents_Call{Call: _e.mock.On("GetFileContents", ctx, owner, repo, path, ref)}
}

func (_c *MockGitHubClient_GetFileContents_Call) Run(run func(ctx context.Context, owner string, repo string, path string, ref string)) *MockGitHubClient_GetFileContents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitHubClient_GetFileContents_Call) Return(s string, err error) *MockGitHubClient_GetFileContents_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitHubClient_GetFileContents_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, path string, ref string) (string, error)) *MockGitHubClient_GetFileContents_Call {
	_c.Call.Return(run)
	return _c
}

// GetPullRequestByBranch provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetPullRequestByBranch(ctx context.Context, owner string, repo string, branch string, state string) (*github.PullRequest, error) {
	ret := _mock.Called(ctx, owner, repo, branch, state)

	if len(ret) == 0 {
		panic("no return value specified for GetPullRequestByBranch")
	}

	var r0 *github.PullRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*github.PullRequest, error)); ok {
		return returnFunc(ctx, owner, repo, branch, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, branch, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, branch, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_GetPullRequestByBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPullRequestByBranch'
type MockGitHubClient_GetPullRequestByBranch_Call struct {
	*mock.Call
}

// GetPullRequestByBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - branch string
//   - state string
func (_e *MockGitHubClient_Expecter) GetPullRequestByBranch(ctx interface{}, owner interface{}, repo interface{}, branch interface{}, state interface{}) *MockGitHubClient_GetPullRequestByBranch_Call {
	return &MockGitHubClient_GetPullRequestByBranch_Call{Call: _e.mock.On("GetPullRequestByBranch", ctx, owner, repo, branch, state)}
}

func (_c *MockGitHubClient_GetPullRequestByBranch_Call) Run(run func(ctx context.Context, owner string, repo string, branch string, state string)) *MockGitHubClient_GetPullRequestByBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitHubClient_GetPullRequestByBranch_Call) Return(pullRequest *github.PullRequest, err error) *MockGitHubClient_GetPullRequestByBranch_Call {
	_c.Call.Return(pullRequest, err)
	return _c
}

func (_c *MockGitHubClient_GetPullRequestByBranch_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, branch string, state string) (*github.PullRequest, error)) *MockGitHubClient_GetPullRequestByBranch_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseAssetID provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetReleaseAssetID(ctx context.Context, owner string, repo string, tag string, assetName string) (int64, error) {
	ret := _mock.Called(ctx, owner, repo, tag, assetName)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseAssetID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (int64, error)); ok {
		return returnFunc(ctx, owner, repo, tag, assetName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) int64); ok {
		r0 = returnFunc(ctx, owner, repo, tag, assetName)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, tag, assetName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_GetReleaseAssetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseAssetID'
type MockGitHubClient_GetReleaseAssetID_Call struct {
	*mock.Call
}

// GetReleaseAssetID is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - tag string
//   - assetName string
func (_e *MockGitHubClient_Expecter) GetReleaseAssetID(ctx interface{}, owner interface{}, repo interface{}, tag interface{}, assetName interface{}) *MockGitHubClient_GetReleaseAssetID_Call {
	return &MockGitHubClient_GetReleaseAssetID_Call{Call: _e.mock.On("GetReleaseAssetID", ctx, owner, repo, tag, assetName)}
}

func (_c *MockGitHubClient_GetReleaseAssetID_Call) Run(run func(ctx context.Context, owner string, repo string, tag string, assetName string)) *MockGitHubClient_GetReleaseAssetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitHubClient_GetReleaseAssetID_Call) Return(n int64, err error) *MockGitHubClient_GetReleaseAssetID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGitHubClient_GetReleaseAssetID_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, tag string, assetName string) (int64, error)) *MockGitHubClient_GetReleaseAssetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseAssets provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) GetReleaseAssets(ctx context.Context, owner string, repo string, tag string) ([]*github.ReleaseAsset, error) {
	ret := _mock.Called(ctx, owner, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseAssets")
	}

	var r0 []*github.ReleaseAsset
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) ([]*github.ReleaseAsset, error)); ok {
		return returnFunc(ctx, owner, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) []*github.ReleaseAsset); ok {
		r0 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.ReleaseAsset)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_GetReleaseAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseAssets'
type MockGitHubClient_GetReleaseAssets_Call struct {
	*mock.Call
}

// GetReleaseAssets is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - tag string
func (_e *MockGitHubClient_Expecter) GetReleaseAssets(ctx interface{}, owner interface{}, repo interface{}, tag interface{}) *MockGitHubClient_GetReleaseAssets_Call {
	return &MockGitHubClient_GetReleaseAssets_Call{Call: _e.mock.On("GetReleaseAssets", ctx, owner, repo, tag)}
}

func (_c *MockGitHubClient_GetReleaseAssets_Call) Run(run func(ctx context.Context, owner string, repo string, tag string)) *MockGitHubClient_GetReleaseAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGitHubClient_GetReleaseAssets_Call) Return(releaseAssets []*github.ReleaseAsset, err error) *MockGitHubClient_GetReleaseAssets_Call {
	_c.Call.Return(releaseAssets, err)
	return _c
}

func (_c *MockGitHubClient_GetReleaseAssets_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, tag string) ([]*github.ReleaseAsset, error)) *MockGitHubClient_GetReleaseAssets_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleases provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) ListReleases(ctx context.Context, owner string, repo string) ([]string, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for ListReleases")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitHubClient_ListReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleases'
type MockGitHubClient_ListReleases_Call struct {
	*mock.Call
}

// ListReleases is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockGitHubClient_Expecter) ListReleases(ctx interface{}, owner interface{}, repo interface{}) *MockGitHubClient_ListReleases_Call {
	return &MockGitHubClient_ListReleases_Call{Call: _e.mock.On("ListReleases", ctx, owner, repo)}
}

func (_c *MockGitHubClient_ListReleases_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockGitHubClient_ListReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitHubClient_ListReleases_Call) Return(strings []string, err error) *MockGitHubClient_ListReleases_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGitHubClient_ListReleases_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) ([]string, error)) *MockGitHubClient_ListReleases_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePullRequest provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) UpdatePullRequest(ctx context.Context, owner string, repo string, number int, pull *github.PullRequest) (*github.PullRequest, *github.Response, error) {
	ret := _mock.Called(ctx, owner, repo, number, pull)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePullRequest")
	}

	var r0 *github.PullRequest
	var r1 *github.Response
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, *github.PullRequest) (*github.PullRequest, *github.Response, error)); ok {
		return returnFunc(ctx, owner, repo, number, pull)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, *github.PullRequest) *github.PullRequest); ok {
		r0 = returnFunc(ctx, owner, repo, number, pull)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.PullRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, *github.PullRequest) *github.Response); ok {
		r1 = returnFunc(ctx, owner, repo, number, pull)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int, *github.PullRequest) error); ok {
		r2 = returnFunc(ctx, owner, repo, number, pull)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGitHubClient_UpdatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePullRequest'
type MockGitHubClient_UpdatePullRequest_Call struct {
	*mock.Call
}

// UpdatePullRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - number int
//   - pull *github.PullRequest
func (_e *MockGitHubClient_Expecter) UpdatePullRequest(ctx interface{}, owner interface{}, repo interface{}, number interface{}, pull interface{}) *MockGitHubClient_UpdatePullRequest_Call {
	return &MockGitHubClient_UpdatePullRequest_Call{Call: _e.mock.On("UpdatePullRequest", ctx, owner, repo, number, pull)}
}

func (_c *MockGitHubClient_UpdatePullRequest_Call) Run(run func(ctx context.Context, owner string, repo string, number int, pull *github.PullRequest)) *MockGitHubClient_UpdatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 *github.PullRequest
		if args[4] != nil {
			arg4 = args[4].(*github.PullRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitHubClient_UpdatePullRequest_Call) Return(pullRequest *github.PullRequest, response *github.Response, err error) *MockGitHubClient_UpdatePullRequest_Call {
	_c.Call.Return(pullRequest, response, err)
	return _c
}

func (_c *MockGitHubClient_UpdatePullRequest_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, number int, pull *github.PullRequest) (*github.PullRequest, *github.Response, error)) *MockGitHubClient_UpdatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UploadKey provides a mock function for the type MockGitHubClient
func (_mock *MockGitHubClient) UploadKey(ctx context.Context, name string, key []byte) error {
	ret := _mock.Called(ctx, name, key)

	if len(ret) == 0 {
		panic("no return value specified for UploadKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = returnFunc(ctx, name, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitHubClient_UploadKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadKey'
type MockGitHubClient_UploadKey_Call struct {
	*mock.Call
}

// UploadKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - key []byte
func (_e *MockGitHubClient_Expecter) UploadKey(ctx interface{}, name interface{}, key interface{}) *MockGitHubClient_UploadKey_Call {
	return &MockGitHubClient_UploadKey_Call{Call: _e.mock.On("UploadKey", ctx, name, key)}
}

func (_c *MockGitHubClient_UploadKey_Call) Run(run func(ctx context.Context, name string, key []byte)) *MockGitHubClient_UploadKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitHubClient_UploadKey_Call) Return(err error) *MockGitHubClient_UploadKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitHubClient_UploadKey_Call) RunAndReturn(run func(ctx context.Context, name string, key []byte) error) *MockGitHubClient_UploadKey_Call {
	_c.Call.Return(run)
	return _c
}
