// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/go-git/go-git/v5/plumbing/transport"
	"github.com/go-git/go-git/v5/plumbing/transport/ssh"
	"github.com/phpboyscout/gtb/pkg/vcs/repo"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepoLike creates a new instance of MockRepoLike. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoLike(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoLike {
	mock := &MockRepoLike{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoLike is an autogenerated mock type for the RepoLike type
type MockRepoLike struct {
	mock.Mock
}

type MockRepoLike_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoLike) EXPECT() *MockRepoLike_Expecter {
	return &MockRepoLike_Expecter{mock: &_m.Mock}
}

// AddToFS provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) AddToFS(fs afero.Fs, gitFile *object.File, fullPath string) error {
	ret := _mock.Called(fs, gitFile, fullPath)

	if len(ret) == 0 {
		panic("no return value specified for AddToFS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(afero.Fs, *object.File, string) error); ok {
		r0 = returnFunc(fs, gitFile, fullPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_AddToFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToFS'
type MockRepoLike_AddToFS_Call struct {
	*mock.Call
}

// AddToFS is a helper method to define mock.On call
//   - fs afero.Fs
//   - gitFile *object.File
//   - fullPath string
func (_e *MockRepoLike_Expecter) AddToFS(fs interface{}, gitFile interface{}, fullPath interface{}) *MockRepoLike_AddToFS_Call {
	return &MockRepoLike_AddToFS_Call{Call: _e.mock.On("AddToFS", fs, gitFile, fullPath)}
}

func (_c *MockRepoLike_AddToFS_Call) Run(run func(fs afero.Fs, gitFile *object.File, fullPath string)) *MockRepoLike_AddToFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 afero.Fs
		if args[0] != nil {
			arg0 = args[0].(afero.Fs)
		}
		var arg1 *object.File
		if args[1] != nil {
			arg1 = args[1].(*object.File)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoLike_AddToFS_Call) Return(err error) *MockRepoLike_AddToFS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_AddToFS_Call) RunAndReturn(run func(fs afero.Fs, gitFile *object.File, fullPath string) error) *MockRepoLike_AddToFS_Call {
	_c.Call.Return(run)
	return _c
}

// Checkout provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) Checkout(referenceName plumbing.ReferenceName) error {
	ret := _mock.Called(referenceName)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(plumbing.ReferenceName) error); ok {
		r0 = returnFunc(referenceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockRepoLike_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - referenceName plumbing.ReferenceName
func (_e *MockRepoLike_Expecter) Checkout(referenceName interface{}) *MockRepoLike_Checkout_Call {
	return &MockRepoLike_Checkout_Call{Call: _e.mock.On("Checkout", referenceName)}
}

func (_c *MockRepoLike_Checkout_Call) Run(run func(referenceName plumbing.ReferenceName)) *MockRepoLike_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plumbing.ReferenceName
		if args[0] != nil {
			arg0 = args[0].(plumbing.ReferenceName)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_Checkout_Call) Return(err error) *MockRepoLike_Checkout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_Checkout_Call) RunAndReturn(run func(referenceName plumbing.ReferenceName) error) *MockRepoLike_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// CheckoutCommit provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) CheckoutCommit(hash plumbing.Hash) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckoutCommit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(plumbing.Hash) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_CheckoutCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckoutCommit'
type MockRepoLike_CheckoutCommit_Call struct {
	*mock.Call
}

// CheckoutCommit is a helper method to define mock.On call
//   - hash plumbing.Hash
func (_e *MockRepoLike_Expecter) CheckoutCommit(hash interface{}) *MockRepoLike_CheckoutCommit_Call {
	return &MockRepoLike_CheckoutCommit_Call{Call: _e.mock.On("CheckoutCommit", hash)}
}

func (_c *MockRepoLike_CheckoutCommit_Call) Run(run func(hash plumbing.Hash)) *MockRepoLike_CheckoutCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 plumbing.Hash
		if args[0] != nil {
			arg0 = args[0].(plumbing.Hash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_CheckoutCommit_Call) Return(err error) *MockRepoLike_CheckoutCommit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_CheckoutCommit_Call) RunAndReturn(run func(hash plumbing.Hash) error) *MockRepoLike_CheckoutCommit_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) Clone(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepoLike_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockRepoLike_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockRepoLike_Expecter) Clone(s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockRepoLike_Clone_Call {
	return &MockRepoLike_Clone_Call{Call: _e.mock.On("Clone",
		append([]interface{}{s, s1}, cloneOptions...)...)}
}

func (_c *MockRepoLike_Clone_Call) Run(run func(s string, s1 string, cloneOptions ...repo.CloneOption)) *MockRepoLike_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 2 {
			variadicArgs = args[2].([]repo.CloneOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepoLike_Clone_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockRepoLike_Clone_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockRepoLike_Clone_Call) RunAndReturn(run func(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockRepoLike_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) Commit(s string, commitOptions *git.CommitOptions) (plumbing.Hash, error) {
	ret := _mock.Called(s, commitOptions)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 plumbing.Hash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) (plumbing.Hash, error)); ok {
		return returnFunc(s, commitOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *git.CommitOptions) plumbing.Hash); ok {
		r0 = returnFunc(s, commitOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plumbing.Hash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *git.CommitOptions) error); ok {
		r1 = returnFunc(s, commitOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoLike_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockRepoLike_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - s string
//   - commitOptions *git.CommitOptions
func (_e *MockRepoLike_Expecter) Commit(s interface{}, commitOptions interface{}) *MockRepoLike_Commit_Call {
	return &MockRepoLike_Commit_Call{Call: _e.mock.On("Commit", s, commitOptions)}
}

func (_c *MockRepoLike_Commit_Call) Run(run func(s string, commitOptions *git.CommitOptions)) *MockRepoLike_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *git.CommitOptions
		if args[1] != nil {
			arg1 = args[1].(*git.CommitOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoLike_Commit_Call) Return(hash plumbing.Hash, err error) *MockRepoLike_Commit_Call {
	_c.Call.Return(hash, err)
	return _c
}

func (_c *MockRepoLike_Commit_Call) RunAndReturn(run func(s string, commitOptions *git.CommitOptions) (plumbing.Hash, error)) *MockRepoLike_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBranch provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) CreateBranch(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for CreateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_CreateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBranch'
type MockRepoLike_CreateBranch_Call struct {
	*mock.Call
}

// CreateBranch is a helper method to define mock.On call
//   - s string
func (_e *MockRepoLike_Expecter) CreateBranch(s interface{}) *MockRepoLike_CreateBranch_Call {
	return &MockRepoLike_CreateBranch_Call{Call: _e.mock.On("CreateBranch", s)}
}

func (_c *MockRepoLike_CreateBranch_Call) Run(run func(s string)) *MockRepoLike_CreateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_CreateBranch_Call) Return(err error) *MockRepoLike_CreateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_CreateBranch_Call) RunAndReturn(run func(s string) error) *MockRepoLike_CreateBranch_Call {
	_c.Call.Return(run)
	return _c
}

// DirectoryExists provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) DirectoryExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for DirectoryExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoLike_DirectoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirectoryExists'
type MockRepoLike_DirectoryExists_Call struct {
	*mock.Call
}

// DirectoryExists is a helper method to define mock.On call
//   - s string
func (_e *MockRepoLike_Expecter) DirectoryExists(s interface{}) *MockRepoLike_DirectoryExists_Call {
	return &MockRepoLike_DirectoryExists_Call{Call: _e.mock.On("DirectoryExists", s)}
}

func (_c *MockRepoLike_DirectoryExists_Call) Run(run func(s string)) *MockRepoLike_DirectoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_DirectoryExists_Call) Return(b bool, err error) *MockRepoLike_DirectoryExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepoLike_DirectoryExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockRepoLike_DirectoryExists_Call {
	_c.Call.Return(run)
	return _c
}

// FileExists provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) FileExists(s string) (bool, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for FileExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoLike_FileExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileExists'
type MockRepoLike_FileExists_Call struct {
	*mock.Call
}

// FileExists is a helper method to define mock.On call
//   - s string
func (_e *MockRepoLike_Expecter) FileExists(s interface{}) *MockRepoLike_FileExists_Call {
	return &MockRepoLike_FileExists_Call{Call: _e.mock.On("FileExists", s)}
}

func (_c *MockRepoLike_FileExists_Call) Run(run func(s string)) *MockRepoLike_FileExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_FileExists_Call) Return(b bool, err error) *MockRepoLike_FileExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepoLike_FileExists_Call) RunAndReturn(run func(s string) (bool, error)) *MockRepoLike_FileExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuth provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) GetAuth() transport.AuthMethod {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAuth")
	}

	var r0 transport.AuthMethod
	if returnFunc, ok := ret.Get(0).(func() transport.AuthMethod); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.AuthMethod)
		}
	}
	return r0
}

// MockRepoLike_GetAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuth'
type MockRepoLike_GetAuth_Call struct {
	*mock.Call
}

// GetAuth is a helper method to define mock.On call
func (_e *MockRepoLike_Expecter) GetAuth() *MockRepoLike_GetAuth_Call {
	return &MockRepoLike_GetAuth_Call{Call: _e.mock.On("GetAuth")}
}

func (_c *MockRepoLike_GetAuth_Call) Run(run func()) *MockRepoLike_GetAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepoLike_GetAuth_Call) Return(authMethod transport.AuthMethod) *MockRepoLike_GetAuth_Call {
	_c.Call.Return(authMethod)
	return _c
}

func (_c *MockRepoLike_GetAuth_Call) RunAndReturn(run func() transport.AuthMethod) *MockRepoLike_GetAuth_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) GetFile(s string) (*object.File, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *object.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*object.File, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *object.File); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoLike_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockRepoLike_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - s string
func (_e *MockRepoLike_Expecter) GetFile(s interface{}) *MockRepoLike_GetFile_Call {
	return &MockRepoLike_GetFile_Call{Call: _e.mock.On("GetFile", s)}
}

func (_c *MockRepoLike_GetFile_Call) Run(run func(s string)) *MockRepoLike_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_GetFile_Call) Return(file *object.File, err error) *MockRepoLike_GetFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockRepoLike_GetFile_Call) RunAndReturn(run func(s string) (*object.File, error)) *MockRepoLike_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepo provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) GetRepo() *git.Repository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRepo")
	}

	var r0 *git.Repository
	if returnFunc, ok := ret.Get(0).(func() *git.Repository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	return r0
}

// MockRepoLike_GetRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepo'
type MockRepoLike_GetRepo_Call struct {
	*mock.Call
}

// GetRepo is a helper method to define mock.On call
func (_e *MockRepoLike_Expecter) GetRepo() *MockRepoLike_GetRepo_Call {
	return &MockRepoLike_GetRepo_Call{Call: _e.mock.On("GetRepo")}
}

func (_c *MockRepoLike_GetRepo_Call) Run(run func()) *MockRepoLike_GetRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepoLike_GetRepo_Call) Return(repository *git.Repository) *MockRepoLike_GetRepo_Call {
	_c.Call.Return(repository)
	return _c
}

func (_c *MockRepoLike_GetRepo_Call) RunAndReturn(run func() *git.Repository) *MockRepoLike_GetRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetTree provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) GetTree() *git.Worktree {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTree")
	}

	var r0 *git.Worktree
	if returnFunc, ok := ret.Get(0).(func() *git.Worktree); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Worktree)
		}
	}
	return r0
}

// MockRepoLike_GetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTree'
type MockRepoLike_GetTree_Call struct {
	*mock.Call
}

// GetTree is a helper method to define mock.On call
func (_e *MockRepoLike_Expecter) GetTree() *MockRepoLike_GetTree_Call {
	return &MockRepoLike_GetTree_Call{Call: _e.mock.On("GetTree")}
}

func (_c *MockRepoLike_GetTree_Call) Run(run func()) *MockRepoLike_GetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepoLike_GetTree_Call) Return(worktree *git.Worktree) *MockRepoLike_GetTree_Call {
	_c.Call.Return(worktree)
	return _c
}

func (_c *MockRepoLike_GetTree_Call) RunAndReturn(run func() *git.Worktree) *MockRepoLike_GetTree_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) Open(v repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(v, s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(v, s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(repo.RepoType, string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(v, s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(repo.RepoType, string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(v, s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(repo.RepoType, string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(v, s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(repo.RepoType, string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(v, s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepoLike_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockRepoLike_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - v repo.RepoType
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockRepoLike_Expecter) Open(v interface{}, s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockRepoLike_Open_Call {
	return &MockRepoLike_Open_Call{Call: _e.mock.On("Open",
		append([]interface{}{v, s, s1}, cloneOptions...)...)}
}

func (_c *MockRepoLike_Open_Call) Run(run func(v repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption)) *MockRepoLike_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repo.RepoType
		if args[0] != nil {
			arg0 = args[0].(repo.RepoType)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 3 {
			variadicArgs = args[3].([]repo.CloneOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRepoLike_Open_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockRepoLike_Open_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockRepoLike_Open_Call) RunAndReturn(run func(v repo.RepoType, s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockRepoLike_Open_Call {
	_c.Call.Return(run)
	return _c
}

// OpenInMemory provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) OpenInMemory(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error) {
	var tmpRet mock.Arguments
	if len(cloneOptions) > 0 {
		tmpRet = _mock.Called(s, s1, cloneOptions)
	} else {
		tmpRet = _mock.Called(s, s1)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for OpenInMemory")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1, cloneOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, ...repo.CloneOption) *git.Repository); ok {
		r0 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, ...repo.CloneOption) *git.Worktree); ok {
		r1 = returnFunc(s, s1, cloneOptions...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, ...repo.CloneOption) error); ok {
		r2 = returnFunc(s, s1, cloneOptions...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepoLike_OpenInMemory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenInMemory'
type MockRepoLike_OpenInMemory_Call struct {
	*mock.Call
}

// OpenInMemory is a helper method to define mock.On call
//   - s string
//   - s1 string
//   - cloneOptions ...repo.CloneOption
func (_e *MockRepoLike_Expecter) OpenInMemory(s interface{}, s1 interface{}, cloneOptions ...interface{}) *MockRepoLike_OpenInMemory_Call {
	return &MockRepoLike_OpenInMemory_Call{Call: _e.mock.On("OpenInMemory",
		append([]interface{}{s, s1}, cloneOptions...)...)}
}

func (_c *MockRepoLike_OpenInMemory_Call) Run(run func(s string, s1 string, cloneOptions ...repo.CloneOption)) *MockRepoLike_OpenInMemory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []repo.CloneOption
		var variadicArgs []repo.CloneOption
		if len(args) > 2 {
			variadicArgs = args[2].([]repo.CloneOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRepoLike_OpenInMemory_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockRepoLike_OpenInMemory_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockRepoLike_OpenInMemory_Call) RunAndReturn(run func(s string, s1 string, cloneOptions ...repo.CloneOption) (*git.Repository, *git.Worktree, error)) *MockRepoLike_OpenInMemory_Call {
	_c.Call.Return(run)
	return _c
}

// OpenLocal provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) OpenLocal(s string, s1 string) (*git.Repository, *git.Worktree, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for OpenLocal")
	}

	var r0 *git.Repository
	var r1 *git.Worktree
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*git.Repository, *git.Worktree, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *git.Repository); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *git.Worktree); ok {
		r1 = returnFunc(s, s1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*git.Worktree)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = returnFunc(s, s1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepoLike_OpenLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenLocal'
type MockRepoLike_OpenLocal_Call struct {
	*mock.Call
}

// OpenLocal is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockRepoLike_Expecter) OpenLocal(s interface{}, s1 interface{}) *MockRepoLike_OpenLocal_Call {
	return &MockRepoLike_OpenLocal_Call{Call: _e.mock.On("OpenLocal", s, s1)}
}

func (_c *MockRepoLike_OpenLocal_Call) Run(run func(s string, s1 string)) *MockRepoLike_OpenLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoLike_OpenLocal_Call) Return(repository *git.Repository, worktree *git.Worktree, err error) *MockRepoLike_OpenLocal_Call {
	_c.Call.Return(repository, worktree, err)
	return _c
}

func (_c *MockRepoLike_OpenLocal_Call) RunAndReturn(run func(s string, s1 string) (*git.Repository, *git.Worktree, error)) *MockRepoLike_OpenLocal_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) Push(pushOptions *git.PushOptions) error {
	ret := _mock.Called(pushOptions)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*git.PushOptions) error); ok {
		r0 = returnFunc(pushOptions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockRepoLike_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - pushOptions *git.PushOptions
func (_e *MockRepoLike_Expecter) Push(pushOptions interface{}) *MockRepoLike_Push_Call {
	return &MockRepoLike_Push_Call{Call: _e.mock.On("Push", pushOptions)}
}

func (_c *MockRepoLike_Push_Call) Run(run func(pushOptions *git.PushOptions)) *MockRepoLike_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *git.PushOptions
		if args[0] != nil {
			arg0 = args[0].(*git.PushOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_Push_Call) Return(err error) *MockRepoLike_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_Push_Call) RunAndReturn(run func(pushOptions *git.PushOptions) error) *MockRepoLike_Push_Call {
	_c.Call.Return(run)
	return _c
}

// SetBasicAuth provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SetBasicAuth(s string, s1 string) {
	_mock.Called(s, s1)
	return
}

// MockRepoLike_SetBasicAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBasicAuth'
type MockRepoLike_SetBasicAuth_Call struct {
	*mock.Call
}

// SetBasicAuth is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockRepoLike_Expecter) SetBasicAuth(s interface{}, s1 interface{}) *MockRepoLike_SetBasicAuth_Call {
	return &MockRepoLike_SetBasicAuth_Call{Call: _e.mock.On("SetBasicAuth", s, s1)}
}

func (_c *MockRepoLike_SetBasicAuth_Call) Run(run func(s string, s1 string)) *MockRepoLike_SetBasicAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoLike_SetBasicAuth_Call) Return() *MockRepoLike_SetBasicAuth_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepoLike_SetBasicAuth_Call) RunAndReturn(run func(s string, s1 string)) *MockRepoLike_SetBasicAuth_Call {
	_c.Run(run)
	return _c
}

// SetKey provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SetKey(publicKeys *ssh.PublicKeys) {
	_mock.Called(publicKeys)
	return
}

// MockRepoLike_SetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetKey'
type MockRepoLike_SetKey_Call struct {
	*mock.Call
}

// SetKey is a helper method to define mock.On call
//   - publicKeys *ssh.PublicKeys
func (_e *MockRepoLike_Expecter) SetKey(publicKeys interface{}) *MockRepoLike_SetKey_Call {
	return &MockRepoLike_SetKey_Call{Call: _e.mock.On("SetKey", publicKeys)}
}

func (_c *MockRepoLike_SetKey_Call) Run(run func(publicKeys *ssh.PublicKeys)) *MockRepoLike_SetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ssh.PublicKeys
		if args[0] != nil {
			arg0 = args[0].(*ssh.PublicKeys)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_SetKey_Call) Return() *MockRepoLike_SetKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepoLike_SetKey_Call) RunAndReturn(run func(publicKeys *ssh.PublicKeys)) *MockRepoLike_SetKey_Call {
	_c.Run(run)
	return _c
}

// SetRepo provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SetRepo(repository *git.Repository) {
	_mock.Called(repository)
	return
}

// MockRepoLike_SetRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRepo'
type MockRepoLike_SetRepo_Call struct {
	*mock.Call
}

// SetRepo is a helper method to define mock.On call
//   - repository *git.Repository
func (_e *MockRepoLike_Expecter) SetRepo(repository interface{}) *MockRepoLike_SetRepo_Call {
	return &MockRepoLike_SetRepo_Call{Call: _e.mock.On("SetRepo", repository)}
}

func (_c *MockRepoLike_SetRepo_Call) Run(run func(repository *git.Repository)) *MockRepoLike_SetRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *git.Repository
		if args[0] != nil {
			arg0 = args[0].(*git.Repository)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_SetRepo_Call) Return() *MockRepoLike_SetRepo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepoLike_SetRepo_Call) RunAndReturn(run func(repository *git.Repository)) *MockRepoLike_SetRepo_Call {
	_c.Run(run)
	return _c
}

// SetSource provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SetSource(n int) {
	_mock.Called(n)
	return
}

// MockRepoLike_SetSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSource'
type MockRepoLike_SetSource_Call struct {
	*mock.Call
}

// SetSource is a helper method to define mock.On call
//   - n int
func (_e *MockRepoLike_Expecter) SetSource(n interface{}) *MockRepoLike_SetSource_Call {
	return &MockRepoLike_SetSource_Call{Call: _e.mock.On("SetSource", n)}
}

func (_c *MockRepoLike_SetSource_Call) Run(run func(n int)) *MockRepoLike_SetSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_SetSource_Call) Return() *MockRepoLike_SetSource_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepoLike_SetSource_Call) RunAndReturn(run func(n int)) *MockRepoLike_SetSource_Call {
	_c.Run(run)
	return _c
}

// SetTree provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SetTree(worktree *git.Worktree) {
	_mock.Called(worktree)
	return
}

// MockRepoLike_SetTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTree'
type MockRepoLike_SetTree_Call struct {
	*mock.Call
}

// SetTree is a helper method to define mock.On call
//   - worktree *git.Worktree
func (_e *MockRepoLike_Expecter) SetTree(worktree interface{}) *MockRepoLike_SetTree_Call {
	return &MockRepoLike_SetTree_Call{Call: _e.mock.On("SetTree", worktree)}
}

func (_c *MockRepoLike_SetTree_Call) Run(run func(worktree *git.Worktree)) *MockRepoLike_SetTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *git.Worktree
		if args[0] != nil {
			arg0 = args[0].(*git.Worktree)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_SetTree_Call) Return() *MockRepoLike_SetTree_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepoLike_SetTree_Call) RunAndReturn(run func(worktree *git.Worktree)) *MockRepoLike_SetTree_Call {
	_c.Run(run)
	return _c
}

// SourceIs provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) SourceIs(n int) bool {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for SourceIs")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRepoLike_SourceIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceIs'
type MockRepoLike_SourceIs_Call struct {
	*mock.Call
}

// SourceIs is a helper method to define mock.On call
//   - n int
func (_e *MockRepoLike_Expecter) SourceIs(n interface{}) *MockRepoLike_SourceIs_Call {
	return &MockRepoLike_SourceIs_Call{Call: _e.mock.On("SourceIs", n)}
}

func (_c *MockRepoLike_SourceIs_Call) Run(run func(n int)) *MockRepoLike_SourceIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_SourceIs_Call) Return(b bool) *MockRepoLike_SourceIs_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRepoLike_SourceIs_Call) RunAndReturn(run func(n int) bool) *MockRepoLike_SourceIs_Call {
	_c.Call.Return(run)
	return _c
}

// WalkTree provides a mock function for the type MockRepoLike
func (_mock *MockRepoLike) WalkTree(fn func(*object.File) error) error {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for WalkTree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(func(*object.File) error) error); ok {
		r0 = returnFunc(fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoLike_WalkTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalkTree'
type MockRepoLike_WalkTree_Call struct {
	*mock.Call
}

// WalkTree is a helper method to define mock.On call
//   - fn func(*object.File) error
func (_e *MockRepoLike_Expecter) WalkTree(fn interface{}) *MockRepoLike_WalkTree_Call {
	return &MockRepoLike_WalkTree_Call{Call: _e.mock.On("WalkTree", fn)}
}

func (_c *MockRepoLike_WalkTree_Call) Run(run func(fn func(*object.File) error)) *MockRepoLike_WalkTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(*object.File) error
		if args[0] != nil {
			arg0 = args[0].(func(*object.File) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepoLike_WalkTree_Call) Return(err error) *MockRepoLike_WalkTree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoLike_WalkTree_Call) RunAndReturn(run func(fn func(*object.File) error) error) *MockRepoLike_WalkTree_Call {
	_c.Call.Return(run)
	return _c
}
