// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errorhandling

import (
	"github.com/spf13/cobra"
	mock "github.com/stretchr/testify/mock"
)

// NewMockErrorHandler creates a new instance of MockErrorHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandler {
	mock := &MockErrorHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorHandler is an autogenerated mock type for the ErrorHandler type
type MockErrorHandler struct {
	mock.Mock
}

type MockErrorHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandler) EXPECT() *MockErrorHandler_Expecter {
	return &MockErrorHandler_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Check(err error, prefix string, level string, cmd ...*cobra.Command) {
	if len(cmd) > 0 {
		_mock.Called(err, prefix, level, cmd)
	} else {
		_mock.Called(err, prefix, level)
	}

	return
}

// MockErrorHandler_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockErrorHandler_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - err error
//   - prefix string
//   - level string
//   - cmd ...*cobra.Command
func (_e *MockErrorHandler_Expecter) Check(err interface{}, prefix interface{}, level interface{}, cmd ...interface{}) *MockErrorHandler_Check_Call {
	return &MockErrorHandler_Check_Call{Call: _e.mock.On("Check",
		append([]interface{}{err, prefix, level}, cmd...)...)}
}

func (_c *MockErrorHandler_Check_Call) Run(run func(err error, prefix string, level string, cmd ...*cobra.Command)) *MockErrorHandler_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []*cobra.Command
		var variadicArgs []*cobra.Command
		if len(args) > 3 {
			variadicArgs = args[3].([]*cobra.Command)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Check_Call) Return() *MockErrorHandler_Check_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Check_Call) RunAndReturn(run func(err error, prefix string, level string, cmd ...*cobra.Command)) *MockErrorHandler_Check_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Error(err error, prefixes ...string) {
	if len(prefixes) > 0 {
		_mock.Called(err, prefixes)
	} else {
		_mock.Called(err)
	}

	return
}

// MockErrorHandler_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockErrorHandler_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
//   - prefixes ...string
func (_e *MockErrorHandler_Expecter) Error(err interface{}, prefixes ...interface{}) *MockErrorHandler_Error_Call {
	return &MockErrorHandler_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{err}, prefixes...)...)}
}

func (_c *MockErrorHandler_Error_Call) Run(run func(err error, prefixes ...string)) *MockErrorHandler_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Error_Call) Return() *MockErrorHandler_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Error_Call) RunAndReturn(run func(err error, prefixes ...string)) *MockErrorHandler_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Fatal(err error, prefixes ...string) {
	if len(prefixes) > 0 {
		_mock.Called(err, prefixes)
	} else {
		_mock.Called(err)
	}

	return
}

// MockErrorHandler_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockErrorHandler_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - err error
//   - prefixes ...string
func (_e *MockErrorHandler_Expecter) Fatal(err interface{}, prefixes ...interface{}) *MockErrorHandler_Fatal_Call {
	return &MockErrorHandler_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{err}, prefixes...)...)}
}

func (_c *MockErrorHandler_Fatal_Call) Run(run func(err error, prefixes ...string)) *MockErrorHandler_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Fatal_Call) Return() *MockErrorHandler_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Fatal_Call) RunAndReturn(run func(err error, prefixes ...string)) *MockErrorHandler_Fatal_Call {
	_c.Run(run)
	return _c
}

// SetUsage provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) SetUsage(usage func() error) {
	_mock.Called(usage)
	return
}

// MockErrorHandler_SetUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsage'
type MockErrorHandler_SetUsage_Call struct {
	*mock.Call
}

// SetUsage is a helper method to define mock.On call
//   - usage func() error
func (_e *MockErrorHandler_Expecter) SetUsage(usage interface{}) *MockErrorHandler_SetUsage_Call {
	return &MockErrorHandler_SetUsage_Call{Call: _e.mock.On("SetUsage", usage)}
}

func (_c *MockErrorHandler_SetUsage_Call) Run(run func(usage func() error)) *MockErrorHandler_SetUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockErrorHandler_SetUsage_Call) Return() *MockErrorHandler_SetUsage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_SetUsage_Call) RunAndReturn(run func(usage func() error)) *MockErrorHandler_SetUsage_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockErrorHandler
func (_mock *MockErrorHandler) Warn(err error, prefixes ...string) {
	if len(prefixes) > 0 {
		_mock.Called(err, prefixes)
	} else {
		_mock.Called(err)
	}

	return
}

// MockErrorHandler_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockErrorHandler_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - err error
//   - prefixes ...string
func (_e *MockErrorHandler_Expecter) Warn(err interface{}, prefixes ...interface{}) *MockErrorHandler_Warn_Call {
	return &MockErrorHandler_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{err}, prefixes...)...)}
}

func (_c *MockErrorHandler_Warn_Call) Run(run func(err error, prefixes ...string)) *MockErrorHandler_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockErrorHandler_Warn_Call) Return() *MockErrorHandler_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockErrorHandler_Warn_Call) RunAndReturn(run func(err error, prefixes ...string)) *MockErrorHandler_Warn_Call {
	_c.Run(run)
	return _c
}
