package templates

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/dave/jennifer/jen"
)

type CommandFlag struct {
	Name          string
	Type          string
	Description   string
	Persistent    bool
	Shorthand     string
	Default       string
	DefaultIsCode bool
	Required      bool
	Hidden        bool
}

type CommandData struct {
	Package                  string
	PascalName               string
	Name                     string
	Aliases                  []string
	Args                     string
	Short                    string
	Long                     string
	Hidden                   bool
	WithAssets               bool
	Flags                    []CommandFlag
	PersistentFlags          []CommandFlag
	AncestralPersistentFlags []CommandFlag
	MutuallyExclusive        [][]string
	RequiredTogether         [][]string
	Logic                    string
	Imports                  []string
	FullFileContent          string
	TestCode                 string
	Recommendations          []string
	PersistentPreRun         bool
	PreRun                   bool
	HasSubcommands           bool
	OmitRun                  bool
	WithInitializer          bool
	Hashes                   map[string]string
}

func CommandRegistration(data CommandData) *jen.File {
	f := jen.NewFile(data.Package)
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	if data.WithAssets {
		f.Comment("//go:embed assets/*")
		f.Var().Id("assets").Qual("embed", "FS")
	}

	generateOptionsStruct(f, data)
	generateConstants(f, data)
	generateNewCmdFunction(f, data)

	return f
}

func generateConstants(f *jen.File, data CommandData) {
	var constants []jen.Code

	allFlags := append([]CommandFlag{}, data.Flags...)
	allFlags = append(allFlags, data.PersistentFlags...)
	allFlags = append(allFlags, data.AncestralPersistentFlags...)

	for _, flag := range allFlags {
		if c, ok := getConstantForFlag(flag); ok {
			constants = append(constants, c)
		}
	}

	if len(constants) > 0 {
		f.Const().Defs(constants...)
		f.Line()
	}
}

func getConstantForFlag(flag CommandFlag) (jen.Code, bool) {
	if flag.Default == "" || flag.DefaultIsCode {
		return nil, false
	}

	if flag.Type == "string" || flag.Type == "bool" || flag.Type == "" {
		return nil, false
	}

	constName := "default" + pascalCase(flag.Name)
	val := getConstantValue(flag)

	if val == nil {
		return nil, false
	}

	return jen.Id(constName).Op("=").Add(val), true
}

func getConstantValue(flag CommandFlag) jen.Code {
	switch flag.Type {
	case "int", "int32", "int64", "uint", "uint32", "uint64":
		return getIntConstantValue(flag)
	case "float64":
		f, _ := strconv.ParseFloat(flag.Default, 64)

		return jen.Id("float64").Call(jen.Lit(f))
	case "duration":
		return getDurationConstantValue(flag)
	}

	return nil
}

func getIntConstantValue(flag CommandFlag) jen.Code {
	i, _ := strconv.ParseInt(flag.Default, 10, 64)
	// Explicitly type the constant to match the flag type
	goType := flag.Type
	if goType == "" {
		goType = "int"
	}

	if flag.Type == "int64" || flag.Type == "uint64" {
		return jen.Lit(i)
	}

	return jen.Id(goType).Call(jen.Lit(int(i)))
}

func getDurationConstantValue(flag CommandFlag) jen.Code {
	d := parseDuration(flag.Default)

	switch {
	case d%time.Hour == 0 && d > 0:
		return jen.Lit(int(d.Hours())).Op("*").Qual("time", "Hour")
	case d%time.Minute == 0 && d > 0:
		return jen.Lit(int(d.Minutes())).Op("*").Qual("time", "Minute")
	case d%time.Second == 0 && d > 0:
		return jen.Lit(int(d.Seconds())).Op("*").Qual("time", "Second")
	case d%time.Millisecond == 0 && d > 0:
		return jen.Lit(int(d.Milliseconds())).Op("*").Qual("time", "Millisecond")
	default:
		return jen.Qual("time", "Duration").Call(jen.Lit(int(d)))
	}
}

func parseDuration(s string) time.Duration {
	if s == "" {
		return 0
	}

	// If it's just a number, treat as seconds
	if _, err := time.ParseDuration(s); err != nil {
		if d, err := time.ParseDuration(s + "s"); err == nil {
			return d
		}
	} else if d, err := time.ParseDuration(s); err == nil {
		return d
	}

	return 0
}

func generateOptionsStruct(f *jen.File, data CommandData) {
	f.Type().Id(data.PascalName + "Options").StructFunc(func(g *jen.Group) {
		// Duplicated ancestral persistent flags
		for _, flag := range data.AncestralPersistentFlags {
			addFlagToStruct(g, flag)
		}

		// Own persistent flags
		for _, flag := range data.PersistentFlags {
			addFlagToStruct(g, flag)
		}

		// Own normal flags
		for _, flag := range data.Flags {
			if flag.Persistent {
				continue
			}

			addFlagToStruct(g, flag)
		}
	})
	f.Line()
}

func addFlagToStruct(g *jen.Group, flag CommandFlag) {
	typeName := flag.Type
	if typeName == "" {
		typeName = "string"
	}
	// Map manifest types to Go types
	goType := typeName
	switch typeName {
	case "stringSlice", "stringslice":
		goType = "[]string"
	case "intSlice", "intslice":
		goType = "[]int"
	case "int32":
		goType = "int32"
	case "uint":
		goType = "uint"
	case "uint32":
		goType = "uint32"
	case "uint64":
		goType = "uint64"
	case "duration":
		g.Id(pascalCase(flag.Name)).Qual("time", "Duration")

		return
	}

	g.Id(pascalCase(flag.Name)).Id(goType)
}

func generateNewCmdFunction(f *jen.File, data CommandData) {
	returns := []jen.Code{
		jen.Op("*").Qual("github.com/spf13/cobra", "Command"),
	}

	params := []jen.Code{
		jen.Id("props").Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props"),
	}

	f.Func().Id("NewCmd" + data.PascalName).Params(params...).Params(returns...).BlockFunc(func(g *jen.Group) {
		if data.WithAssets {
			g.Id("props").Dot("Assets").Dot("Register").Call(jen.Lit(data.Name), jen.Op("&").Id("assets"))
			g.Line()
		}

		if needsOpts(data) {
			g.Id("opts").Op(":=").Op("&").Id(data.PascalName + "Options").Block()
			g.Line()
		}

		cmdFields := generateCommandFields(data)

		g.Id("cmd").Op(":=").Op("&").Qual("github.com/spf13/cobra", "Command").Block(cmdFields...)
		g.Line()

		addFlagsToCommand(g, data.Flags, data.PersistentFlags)
		generateMutuallyExclusive(g, data.MutuallyExclusive)
		generateRequiredTogether(g, data.RequiredTogether)

		g.Return(jen.Id("cmd"))
	})
}

func CommandInitializer(data CommandData) *jen.File {
	f := jen.NewFile(data.Package)
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.Line()
	f.Func().Id("init").Params().Block(
		jen.Qual("github.com/phpboyscout/gtb/pkg/setup", "Register").Call(
			jen.Qual("github.com/phpboyscout/gtb/pkg/props", "FeatureCmd").Call(jen.Lit(data.Name)),
			jen.Index().Qual("github.com/phpboyscout/gtb/pkg/setup", "InitialiserProvider").Values(
				jen.Func().Params(jen.Id("p").Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props")).Qual("github.com/phpboyscout/gtb/pkg/setup", "Initialiser").Block(
					jen.If(jen.Id("skip"+data.PascalName)).Block(jen.Return(jen.Nil())),
					jen.Return(jen.Op("&").Id(data.PascalName+"Initialiser").Block()),
				),
			),
			jen.Index().Qual("github.com/phpboyscout/gtb/pkg/setup", "SubcommandProvider").Values(
				jen.Func().Params(jen.Id("p").Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props")).Index().Op("*").Qual("github.com/spf13/cobra", "Command").Block(
					jen.Return(jen.Index().Op("*").Qual("github.com/spf13/cobra", "Command").Values(jen.Id("NewCmdInit"+data.PascalName).Call(jen.Id("p")))),
				),
			),
			jen.Index().Qual("github.com/phpboyscout/gtb/pkg/setup", "FeatureFlag").Values(
				jen.Func().Params(jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command")).Block(
					jen.Id("cmd").Dot("Flags").Call().Dot("BoolVar").Call(
						jen.Op("&").Id("skip"+data.PascalName),
						jen.Lit("skip-"+data.Name),
						jen.False(),
						jen.Lit("skip initializing "+data.Name+" configuration"),
					),
				),
			),
		),
	)

	f.Var().Id("skip" + data.PascalName).Bool()

	f.Line()
	f.Type().Id(data.PascalName + "Initialiser").Struct()

	f.Func().Params(jen.Id("i").Op("*").Id(data.PascalName + "Initialiser")).Id("Name").Params().String().Block(
		jen.Return(jen.Lit(data.Name)),
	)

	f.Func().Params(jen.Id("i").Op("*").Id(data.PascalName + "Initialiser")).Id("IsConfigured").Params(jen.Id("cfg").Qual("github.com/phpboyscout/gtb/pkg/config", "Containable")).Bool().Block(
		jen.Return(jen.Id("cfg").Dot("IsSet").Call(jen.Lit(data.Name))),
	)

	f.Func().Params(jen.Id("i").Op("*").Id(data.PascalName+"Initialiser")).Id("Configure").Params(jen.Id("p").Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props"), jen.Id("cfg").Qual("github.com/phpboyscout/gtb/pkg/config", "Containable")).Error().Block(
		jen.Return(jen.Id("Init"+data.PascalName).Call(jen.Id("p"), jen.Id("cfg"))),
	)

	f.Line()
	f.Func().Id("NewCmdInit"+data.PascalName).Params(
		jen.Id("p").Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props"),
	).Op("*").Qual("github.com/spf13/cobra", "Command").Block(
		jen.Return(jen.Op("&").Qual("github.com/spf13/cobra", "Command").Values(jen.Dict{
			jen.Id("Use"):   jen.Lit(data.Name),
			jen.Id("Short"): jen.Lit("Initialise " + data.Name + " configuration"),
			jen.Id("RunE"): jen.Func().Params(jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command"), jen.Id("args").Index().String()).Error().Block(
				jen.Return(jen.Id("Init"+data.PascalName).Call(jen.Id("p"), jen.Id("p").Dot("Config"))),
			),
		})),
	)

	return f
}

func needsOpts(data CommandData) bool {
	return !data.OmitRun || data.PersistentPreRun || data.PreRun || len(data.Flags) > 0 || len(data.PersistentFlags) > 0 || len(data.AncestralPersistentFlags) > 0
}

func generateCommandFields(data CommandData) []jen.Code {
	cmdFields := []jen.Code{
		jen.Id("Use").Op(":").Lit(data.Name).Op(","),
		jen.Id("Short").Op(":").Add(litOrRaw(data.Short)).Op(","),
		jen.Id("Long").Op(":").Add(litOrRaw(data.Long)).Op(","),
	}

	if argsField := generateArgsField(data.Args); argsField != nil {
		cmdFields = append(cmdFields, argsField)
	}

	if len(data.Aliases) > 0 {
		cmdFields = append(cmdFields, jen.Id("Aliases").Op(":").Index().String().ValuesFunc(func(g *jen.Group) {
			for _, alias := range data.Aliases {
				g.Lit(alias)
			}
		}).Op(","))
	}

	if data.Hidden {
		cmdFields = append(cmdFields, jen.Id("Hidden").Op(":").True().Op(","))
	}

	if data.PersistentPreRun {
		cmdFields = append(cmdFields, jen.Id("PersistentPreRunE").Op(":").Func().Params(
			jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command"),
			jen.Id("args").Index().String(),
		).Error().Block(
			jen.If(
				jen.Id("cmd").Dot("Parent").Call().Op("!=").Nil().
					Op("&&").Id("cmd").Dot("Parent").Call().Dot("PersistentPreRunE").Op("!=").Nil(),
			).Block(
				jen.If(
					jen.Id("err").Op(":=").Id("cmd").Dot("Parent").Call().Dot("PersistentPreRunE").Call(jen.Id("cmd"), jen.Id("args")).Op(";").
						Id("err").Op("!=").Nil(),
				).Block(
					jen.Return(jen.Id("err")),
				),
			),
			jen.Return(
				jen.Id("PersistentPreRun"+data.PascalName).Call(
					jen.Id("cmd").Dot("Context").Call(),
					jen.Id("props"),
					jen.Id("opts"),
					jen.Id("args"),
				),
			),
		).Op(","))
	}

	cmdFields = append(cmdFields, generatePreRunField(data))

	if !data.OmitRun {
		cmdFields = append(cmdFields, jen.Id("RunE").Op(":").Func().Params(
			jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command"),
			jen.Id("args").Index().String(),
		).Error().Block(
			jen.Return(
				jen.Id("Run"+data.PascalName).Call(
					jen.Id("cmd").Dot("Context").Call(),
					jen.Id("props"),
					jen.Id("opts"),
					jen.Id("args"),
				),
			),
		).Op(","))
	}

	return cmdFields
}

func generatePreRunField(data CommandData) jen.Code {
	return jen.Id("PreRunE").Op(":").Func().Params(
		jen.Id("cmd").Op("*").Qual("github.com/spf13/cobra", "Command"),
		jen.Id("args").Index().String(),
	).Error().BlockFunc(func(bg *jen.Group) {
		// Pull ancestral persistent flag values
		for _, flag := range data.AncestralPersistentFlags {
			pullFlag(bg, flag)
		}

		bg.Id("props").Dot("ErrorHandler").Dot("SetUsage").Call(jen.Id("cmd").Dot("Usage"))

		if data.PreRun {
			bg.Return(
				jen.Id("PreRun"+data.PascalName).Call(
					jen.Id("cmd").Dot("Context").Call(),
					jen.Id("props"),
					jen.Id("opts"),
					jen.Id("args"),
				),
			)
		} else {
			bg.Return(jen.Nil())
		}
	}).Op(",")
}

func generateMutuallyExclusive(g *jen.Group, groups [][]string) {
	for _, group := range groups {
		if len(group) > 1 {
			args := make([]jen.Code, 0, len(group))
			for _, flagName := range group {
				args = append(args, jen.Lit(flagName))
			}

			g.Id("cmd").Dot("MarkFlagsMutuallyExclusive").Call(args...)
		}
	}
}

func generateRequiredTogether(g *jen.Group, groups [][]string) {
	for _, group := range groups {
		if len(group) > 1 {
			args := make([]jen.Code, 0, len(group))
			for _, flagName := range group {
				args = append(args, jen.Lit(flagName))
			}

			g.Id("cmd").Dot("MarkFlagsRequiredTogether").Call(args...)
		}
	}
}

func addFlagsToCommand(g *jen.Group, flags []CommandFlag, persistentFlags []CommandFlag) {
	// Add ancestral persistent flags (already bound in parent, but we might want to bind them here if we want local access?
	// Actually in cobra, persistent flags are inherited. We only need to bind them if we want to OVERRIDE or if we are the ones DEFINING them.
	// But our "functional" model means we have a local copy of the value.
	// Wait, if we define them again here, it might conflict?
	// Cobra: "Persistent Flags: A flag can be persistent, meaning that this flag will be available to the command it's assigned to as well as every command under that command."
	// So we don't re-define ancestral flags. We only bind OUR OWN flags.
	// Our 'populate' callback handles receiving values from parents.

	// Add normal flags
	for _, flag := range flags {
		if flag.Persistent {
			continue
		}

		addFlag(g, flag, false)
	}

	// Add persistent flags
	for _, flag := range persistentFlags {
		addFlag(g, flag, true)
	}

	if len(flags) > 0 || len(persistentFlags) > 0 {
		g.Line()
	}
}

func addFlag(g *jen.Group, flag CommandFlag, isPersistent bool) {
	funcName, defaultVal := getFlagFunctionAndDefault(flag)

	if flag.Shorthand != "" {
		funcName += "P"
	}

	fGroup := jen.Id("cmd").Dot("Flags").Call()
	if isPersistent {
		fGroup = jen.Id("cmd").Dot("PersistentFlags").Call()
	}

	args := []jen.Code{
		jen.Op("&").Id("opts").Dot(pascalCase(flag.Name)),
		jen.Lit(flag.Name),
	}

	if flag.Shorthand != "" {
		args = append(args, jen.Lit(flag.Shorthand))
	}

	args = append(args, defaultVal, litOrRaw(flag.Description))

	g.Add(fGroup.Dot(funcName).Call(args...))

	if flag.Required {
		markFuncName := "MarkFlagRequired"
		if isPersistent {
			markFuncName = "MarkPersistentFlagRequired"
		}

		g.Id("_").Op("=").Id("cmd").Dot(markFuncName).Call(jen.Lit(flag.Name))
	}

	if flag.Hidden {
		g.Id("_").Op("=").Id("cmd").Dot("Flags").Call().Dot("MarkHidden").Call(jen.Lit(flag.Name))
	}
}

func pullFlag(g *jen.Group, flag CommandFlag) {
	funcSuffix := "String"

	switch flag.Type {
	case "bool":
		funcSuffix = "Bool"
	case "int":
		funcSuffix = "Int"
	case "float64":
		funcSuffix = "Float64"
	case "stringSlice", "stringslice":
		funcSuffix = "StringSlice"
	case "intSlice", "intslice":
		funcSuffix = "IntSlice"
	case "int64":
		funcSuffix = "Int64"
	case "duration":
		funcSuffix = "Duration"
	}

	g.If(
		jen.List(jen.Id("v"), jen.Id("err")).Op(":=").Id("cmd").Dot("Flags").Call().Dot("Get"+funcSuffix).Call(jen.Lit(flag.Name)),
		jen.Id("err").Op("==").Nil(),
	).Block(
		jen.Id("opts").Dot(pascalCase(flag.Name)).Op("=").Id("v"),
	)
}

func getFlagFunctionAndDefault(flag CommandFlag) (string, jen.Code) {
	funcName := getFlagFuncName(flag.Type)
	defaultVal := getFlagDefaultValue(flag)

	return funcName, defaultVal
}

func getFlagFuncName(flagType string) string {
	if fn, ok := flagFuncMap[flagType]; ok {
		return fn
	}

	return "StringVar"
}

var flagFuncMap = map[string]string{
	"bool":        "BoolVar",
	"int":         "IntVar",
	"float64":     "Float64Var",
	"stringSlice": "StringSliceVar",
	"stringslice": "StringSliceVar",
	"intSlice":    "IntSliceVar",
	"intslice":    "IntSliceVar",
	"int32":       "Int32Var",
	"int64":       "Int64Var",
	"uint":        "UintVar",
	"uint32":      "Uint32Var",
	"uint64":      "Uint64Var",
	"duration":    "DurationVar",
}

func getFlagDefaultValue(flag CommandFlag) jen.Code {
	if flag.Default == "" {
		return getZeroValue(flag.Type)
	}

	if flag.DefaultIsCode {
		return jen.Id(flag.Default)
	}

	switch flag.Type {
	case "bool":
		if flag.Default == "true" {
			return jen.True()
		}

		return jen.False()
	case "stringSlice", "stringslice":
		return getStringSliceDefault(flag.Default)
	case "intSlice", "intslice":
		return getIntSliceDefault(flag.Default)
	case "int", "float64", "int32", "int64", "uint", "uint32", "uint64", "duration":
		return jen.Id("default" + pascalCase(flag.Name))
	}

	// Default to string literal
	return jen.Lit(flag.Default)
}

func getZeroValue(flagType string) jen.Code {
	switch flagType {
	case "bool":
		return jen.False()
	case "int", "int32", "int64", "uint", "uint32", "uint64", "duration":
		return jen.Lit(0)
	case "float64":
		return jen.Lit(0.0)
	case "stringSlice", "stringslice":
		return jen.Index().String().Values()
	case "intSlice", "intslice":
		return jen.Index().Int().Values()
	}

	return jen.Lit("")
}

func getStringSliceDefault(def string) jen.Code {
	if def == "[]" {
		return jen.Index().String().Values()
	}

	parts := strings.Split(def, ",")
	vals := make([]jen.Code, len(parts))

	for i, p := range parts {
		vals[i] = jen.Lit(strings.TrimSpace(p))
	}

	return jen.Index().String().Values(vals...)
}

func getIntSliceDefault(def string) jen.Code {
	if def == "[]" {
		return jen.Index().Int().Values()
	}

	parts := strings.Split(def, ",")
	vals := make([]jen.Code, len(parts))

	for i, p := range parts {
		iv, _ := strconv.Atoi(strings.TrimSpace(p))
		vals[i] = jen.Lit(iv)
	}

	return jen.Index().Int().Values(vals...)
}

func CommandExecution(data CommandData) string {
	if data.FullFileContent != "" {
		return data.FullFileContent
	}

	cleanImports := getCleanImports(data.Imports, data.WithInitializer)

	var sb strings.Builder
	sb.WriteString("package " + data.Package + "\n\n")
	sb.WriteString("import (\n")

	for _, imp := range cleanImports {
		if strings.Contains(imp, "\"") {
			sb.WriteString("\t" + imp + "\n")
		} else {
			sb.WriteString("\t\"" + imp + "\"\n")
		}
	}

	sb.WriteString(")\n\n")

	if data.PersistentPreRun {
		fmt.Fprintf(&sb, "func PersistentPreRun%s(ctx context.Context, props *props.Props, opts *%sOptions, args []string) error {\n", data.PascalName, data.PascalName)
		sb.WriteString("\tprops.Logger.Info(\"Running persistent pre run for " + data.Name + "\")\n")
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")
	}

	if data.PreRun {
		fmt.Fprintf(&sb, "func PreRun%s(ctx context.Context, props *props.Props, opts *%sOptions, args []string) error {\n", data.PascalName, data.PascalName)
		sb.WriteString("\tprops.Logger.Info(\"Running pre run for " + data.Name + "\")\n")
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n\n")
	}

	fmt.Fprintf(&sb, "func Run%s(ctx context.Context, props *props.Props, opts *%sOptions, args []string) error {\n", data.PascalName, data.PascalName)

	if data.Logic != "" {
		sb.WriteString(data.Logic)
		sb.WriteString("\n")
	} else {
		if data.HasSubcommands {
			sb.WriteString("\treturn errorhandling.ErrRunSubCommand\n")
		} else {
			sb.WriteString("\treturn errorhandling.ErrNotImplemented\n")
		}
	}

	if data.WithInitializer {
		sb.WriteString("\n")
		fmt.Fprintf(&sb, "func Init%s(p *props.Props, cfg config.Containable) error {\n", data.PascalName)
		sb.WriteString("\t// TODO: Implement custom initialization logic for " + data.Name + "\n")
		sb.WriteString("\treturn nil\n")
		sb.WriteString("}\n")
	}

	return sb.String()
}

func getCleanImports(rawImports []string, withInitializer bool) []string {
	uniqueImports := make(map[string]bool)

	var cleanImports []string

	// Add base imports first
	baseImports := []string{
		"context",
		"github.com/phpboyscout/gtb/pkg/props",
		"github.com/phpboyscout/gtb/pkg/errorhandling",
	}

	if withInitializer {
		baseImports = append(baseImports, "github.com/spf13/viper")
	}

	for _, imp := range baseImports {
		uniqueImports[imp] = true
		cleanImports = append(cleanImports, imp)
	}

	for _, imp := range rawImports {
		if isRedundantImport(imp) {
			continue
		}

		if _, exists := uniqueImports[imp]; !exists {
			uniqueImports[imp] = true
			cleanImports = append(cleanImports, imp)
		}
	}

	return cleanImports
}

func isRedundantImport(imp string) bool {
	// Skip redundant props or context imports from AI
	if strings.HasSuffix(imp, "/props") || imp == "context" || imp == "io" || imp == "os" || imp == "fmt" {
		return true
	}

	// Skip hallucinated logger
	if imp == "github.com/phpboyscout/logger" || imp == "github.com/charmbracelet/log" {
		return true
	}

	return false
}

func pascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}

	return strings.Join(parts, "")
}

func litOrRaw(s string) jen.Code {
	if strings.Contains(s, "\n") && !strings.Contains(s, "`") {
		return jen.Id("`" + s + "`")
	}

	return jen.Lit(s)
}

func generateArgsField(args string) jen.Code {
	if args == "" {
		return nil
	}

	callName := strings.Split(args, "(")[0]

	return jen.Id("Args").Op(":").Qual("github.com/spf13/cobra", callName).Add(func() jen.Code {
		if !strings.Contains(args, "(") {
			return jen.Null()
		}

		argStr := strings.TrimSuffix(strings.Split(args, "(")[1], ")")
		if argStr == "" {
			return jen.Call()
		}

		// Check if it's a number
		if i, err := strconv.Atoi(argStr); err == nil {
			return jen.Call(jen.Lit(i))
		}

		return jen.Call(jen.Id(argStr))
	}()).Op(",")
}
