package templates

import (
	"github.com/dave/jennifer/jen"
)

type SkeletonRootData struct {
	Name             string
	Description      string
	ReleaseProvider  string
	Host             string
	Org              string
	RepoName         string
	Private          bool
	DisabledFeatures []string
	EnabledFeatures  []string
	HelpType         string // "slack", "teams", or ""
	SlackChannel     string
	SlackTeam        string
	TeamsChannel     string
	TeamsTeam        string
}

func SkeletonRoot(data SkeletonRootData) *jen.File {
	f := jen.NewFile("root")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.Comment("//go:embed assets/*")
	f.Var().Id("assets").Qual("embed", "FS")

	f.ImportAlias("github.com/phpboyscout/gtb/pkg/cmd/root", "gtbRoot")

	pErrorHandler := jen.Id("p").Dot("ErrorHandler").Op("=").Qual("github.com/phpboyscout/gtb/pkg/errorhandling", "New").Call(jen.Id("logger"), jen.Id("p").Dot("Tool").Dot("Help"))

	rootCmdInit := jen.Id("rootCmd").Op(":=").Qual("github.com/phpboyscout/gtb/pkg/cmd/root", "NewCmdRoot").Call(
		jen.Id("p"),
	)

	toolDict := buildToolDict(data)

	f.Func().Id("NewCmdRoot").Params(
		jen.Id("v").Qual("github.com/phpboyscout/gtb/pkg/version", "Info"),
	).Params(
		jen.Op("*").Qual("github.com/spf13/cobra", "Command"),
		jen.Op("*").Qual("github.com/phpboyscout/gtb/pkg/props", "Props"),
	).Block(
		jen.Id("logger").Op(":=").Qual("github.com/charmbracelet/log", "NewWithOptions").Call(
			jen.Qual("os", "Stderr"),
			jen.Qual("github.com/charmbracelet/log", "Options").Values(jen.Dict{
				jen.Id("ReportCaller"):    jen.False(),
				jen.Id("ReportTimestamp"): jen.True(),
				jen.Id("Level"):           jen.Qual("github.com/charmbracelet/log", "InfoLevel"),
			}),
		),
		jen.Line(),
		jen.Id("p").Op(":=").Op("&").Qual("github.com/phpboyscout/gtb/pkg/props", "Props").Values(jen.Dict{
			jen.Id("Tool"):    jen.Qual("github.com/phpboyscout/gtb/pkg/props", "Tool").Values(toolDict),
			jen.Id("Logger"):  jen.Id("logger"),
			jen.Id("Assets"):  jen.Qual("github.com/phpboyscout/gtb/pkg/props", "NewAssets").Call(jen.Qual("github.com/phpboyscout/gtb/pkg/props", "AssetMap").Values(jen.Dict{jen.Lit("root"): jen.Op("&").Id("assets")})),
			jen.Id("FS"):      jen.Qual("github.com/spf13/afero", "NewOsFs").Call(),
			jen.Id("Version"): jen.Id("v"),
		}),
		jen.Line(),
		pErrorHandler,
		jen.Line(),
		rootCmdInit,
		jen.Line(),
		jen.Return(jen.Id("rootCmd"), jen.Id("p")),
	)

	return f
}

func buildToolDict(data SkeletonRootData) jen.Dict {
	toolDict := jen.Dict{
		jen.Id("Name"):          jen.Lit(data.Name),
		jen.Id("Summary"):       jen.Lit(data.Name + " utility"),
		jen.Id("Description"):   jen.Lit(data.Description),
		jen.Id("ReleaseSource"): jen.Qual("github.com/phpboyscout/gtb/pkg/props", "ReleaseSource").Values(buildReleaseSourceDict(data)),
	}

	switch data.HelpType {
	case "slack":
		toolDict[jen.Id("Help")] = jen.Qual("github.com/phpboyscout/gtb/pkg/errorhandling", "SlackHelp").Values(jen.Dict{
			jen.Id("Channel"): jen.Lit(data.SlackChannel),
			jen.Id("Team"):    jen.Lit(data.SlackTeam),
		})
	case "teams":
		toolDict[jen.Id("Help")] = jen.Qual("github.com/phpboyscout/gtb/pkg/errorhandling", "TeamsHelp").Values(jen.Dict{
			jen.Id("Channel"): jen.Lit(data.TeamsChannel),
			jen.Id("Team"):    jen.Lit(data.TeamsTeam),
		})
	}

	if len(data.DisabledFeatures) > 0 || len(data.EnabledFeatures) > 0 {
		toolDict[jen.Id("Features")] = jen.Qual("github.com/phpboyscout/gtb/pkg/props", "SetFeatures").Call(buildFeatures(data)...)
	}

	return toolDict
}

func buildReleaseSourceDict(data SkeletonRootData) jen.Dict {
	d := jen.Dict{
		jen.Id("Type"):  jen.Lit(data.ReleaseProvider),
		jen.Id("Host"):  jen.Lit(data.Host),
		jen.Id("Owner"): jen.Lit(data.Org),
		jen.Id("Repo"):  jen.Lit(data.RepoName),
	}

	if data.Private {
		d[jen.Id("Private")] = jen.True()
	}

	return d
}

func buildFeatures(data SkeletonRootData) []jen.Code {
	items := []jen.Code{}

	for _, f := range data.DisabledFeatures {
		if cmd := getFeatureCmd(f); cmd != nil {
			items = append(items, jen.Qual("github.com/phpboyscout/gtb/pkg/props", "Disable").Call(cmd))
		}
	}

	for _, f := range data.EnabledFeatures {
		if cmd := getFeatureCmd(f); cmd != nil {
			items = append(items, jen.Qual("github.com/phpboyscout/gtb/pkg/props", "Enable").Call(cmd))
		}
	}

	return items
}

func getFeatureCmd(feature string) jen.Code {
	switch feature {
	case "init":
		return jen.Qual("github.com/phpboyscout/gtb/pkg/props", "InitCmd")
	case "update":
		return jen.Qual("github.com/phpboyscout/gtb/pkg/props", "UpdateCmd")
	case "mcp":
		return jen.Qual("github.com/phpboyscout/gtb/pkg/props", "McpCmd")
	case "docs":
		return jen.Qual("github.com/phpboyscout/gtb/pkg/props", "DocsCmd")
	case "ai":
		return jen.Qual("github.com/phpboyscout/gtb/pkg/props", "AiCmd")
	}

	return nil
}
