package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonMain generates the cmd/<name>/main.go for scaffolded projects.
// It uses the internal/version package to retrieve version info and passes
// it to the root command constructor.
func SkeletonMain(modulePath string) *jen.File {
	f := jen.NewFile("main")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	f.ImportAlias("github.com/phpboyscout/gtb/pkg/cmd/root", "gtbRoot")

	f.Func().Id("main").Params().Block(
		jen.List(jen.Id("rootCmd"), jen.Id("p")).Op(":=").Qual(modulePath+"/pkg/cmd/root", "NewCmdRoot").Call(
			jen.Qual(modulePath+"/internal/version", "Get").Call(),
		),
		jen.Qual("github.com/phpboyscout/gtb/pkg/cmd/root", "Execute").Call(jen.Id("rootCmd"), jen.Id("p")),
	)

	return f
}
