package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonInternalVersion generates the internal/version/version.go file
// for scaffolded projects, mirroring gtb's own internal/version pattern.
func SkeletonInternalVersion(modulePath string) *jen.File {
	f := jen.NewFile("version")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")
	f.ImportAlias("github.com/phpboyscout/gtb/pkg/version", "pkgversion")

	// Package-level vars — injected via ldflags at release, populated from runtime/debug in dev
	f.Var().Defs(
		jen.Id("version").Op("=").Lit("dev"),
		jen.Id("commit").Op("=").Lit("none"),
		jen.Id("date").Op("=").Lit("unknown"),
	)

	// init() function to populate version info from runtime/debug build settings
	f.Func().Id("init").Params().Block(
		jen.List(jen.Id("info"), jen.Id("ok")).Op(":=").Qual("runtime/debug", "ReadBuildInfo").Call(),
		jen.If(jen.Op("!").Id("ok")).Block(
			jen.Return(),
		),
		jen.Line(),
		jen.For(jen.List(jen.Id("_"), jen.Id("setting")).Op(":=").Range().Id("info").Dot("Settings")).Block(
			jen.Switch(jen.Id("setting").Dot("Key")).Block(
				jen.Case(jen.Lit("vcs.revision")).Block(
					jen.Id("commit").Op("=").Id("setting").Dot("Value"),
				),
				jen.Case(jen.Lit("vcs.time")).Block(
					jen.Id("date").Op("=").Id("setting").Dot("Value"),
				),
				jen.Case(jen.Lit("vcs.modified")).Block(
					jen.If(jen.Id("setting").Dot("Value").Op("==").Lit("true")).Block(
						jen.Id("commit").Op("+=").Lit("-dirty"),
					),
				),
			),
		),
		jen.Line(),
		jen.If(jen.Id("version").Op("==").Lit("dev")).Block(
			jen.If(
				jen.Id("info").Dot("Main").Dot("Version").Op("!=").Lit("").
					Op("&&").
					Id("info").Dot("Main").Dot("Version").Op("!=").Lit("(devel)"),
			).Block(
				jen.Id("version").Op("=").Id("info").Dot("Main").Dot("Version"),
			).Else().Block(
				jen.Id("version").Op("=").Id("commit"),
			),
		),
	)

	// Get() function that returns pkgversion.Info
	f.Comment("Get returns the current version information as a pkgversion.Info.")
	f.Func().Id("Get").Params().Qual("github.com/phpboyscout/gtb/pkg/version", "Info").Block(
		jen.Return(jen.Qual("github.com/phpboyscout/gtb/pkg/version", "NewInfo").Call(
			jen.Id("version"), jen.Id("commit"), jen.Id("date"),
		)),
	)

	return f
}
