package templates

import (
	"github.com/dave/jennifer/jen"
)

// SkeletonInternalVersion generates the internal/version/version.go file
// for scaffolded projects, mirroring gtb's own internal/version pattern.
func SkeletonInternalVersion(modulePath string) *jen.File {
	f := jen.NewFile("version")
	f.HeaderComment("Code generated by gtb. DO NOT EDIT.")

	// Package-level vars for ldflags injection
	f.Var().Defs(
		jen.Id("v").Op("=").Lit("dev"),
		jen.Id("c").Op("=").Lit("none"),
		jen.Id("d").Op("=").Lit("unknown"),
	)

	// init() function to read build info at runtime
	f.Func().Id("init").Params().Block(
		jen.If(jen.Id("v").Op("!=").Lit("dev")).Block(
			jen.Return(),
		),
		jen.Line(),
		jen.List(jen.Id("info"), jen.Id("ok")).Op(":=").Qual("runtime/debug", "ReadBuildInfo").Call(),
		jen.If(jen.Op("!").Id("ok")).Block(
			jen.Return(),
		),
		jen.Line(),
		jen.If(jen.Id("info").Dot("Main").Dot("Version").Op("!=").Lit("(devel)")).Block(
			jen.Id("v").Op("=").Id("info").Dot("Main").Dot("Version"),
		),
		jen.Line(),
		jen.For(jen.List(jen.Id("_"), jen.Id("setting")).Op(":=").Range().Id("info").Dot("Settings")).Block(
			jen.Switch(jen.Id("setting").Dot("Key")).Block(
				jen.Case(jen.Lit("vcs.revision")).Block(
					jen.Id("c").Op("=").Id("setting").Dot("Value"),
				),
				jen.Case(jen.Lit("vcs.time")).Block(
					jen.Id("d").Op("=").Id("setting").Dot("Value"),
				),
			),
		),
	)

	// Get() function that returns version.Info
	f.Comment("Get returns the current version information as a version.Info.")
	f.Func().Id("Get").Params().Qual("github.com/phpboyscout/gtb/pkg/version", "Info").Block(
		jen.Return(jen.Qual("github.com/phpboyscout/gtb/pkg/version", "NewInfo").Call(
			jen.Id("v"), jen.Id("c"), jen.Id("d"),
		)),
	)

	return f
}
