// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package version

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersion creates a new instance of MockVersion. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersion(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersion {
	mock := &MockVersion{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersion is an autogenerated mock type for the Version type
type MockVersion struct {
	mock.Mock
}

type MockVersion_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersion) EXPECT() *MockVersion_Expecter {
	return &MockVersion_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type MockVersion
func (_mock *MockVersion) Compare(other string) int {
	ret := _mock.Called(other)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(other)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockVersion_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockVersion_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - other string
func (_e *MockVersion_Expecter) Compare(other interface{}) *MockVersion_Compare_Call {
	return &MockVersion_Compare_Call{Call: _e.mock.On("Compare", other)}
}

func (_c *MockVersion_Compare_Call) Run(run func(other string)) *MockVersion_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersion_Compare_Call) Return(n int) *MockVersion_Compare_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockVersion_Compare_Call) RunAndReturn(run func(other string) int) *MockVersion_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommit provides a mock function for the type MockVersion
func (_mock *MockVersion) GetCommit() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCommit")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVersion_GetCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommit'
type MockVersion_GetCommit_Call struct {
	*mock.Call
}

// GetCommit is a helper method to define mock.On call
func (_e *MockVersion_Expecter) GetCommit() *MockVersion_GetCommit_Call {
	return &MockVersion_GetCommit_Call{Call: _e.mock.On("GetCommit")}
}

func (_c *MockVersion_GetCommit_Call) Run(run func()) *MockVersion_GetCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersion_GetCommit_Call) Return(s string) *MockVersion_GetCommit_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVersion_GetCommit_Call) RunAndReturn(run func() string) *MockVersion_GetCommit_Call {
	_c.Call.Return(run)
	return _c
}

// GetDate provides a mock function for the type MockVersion
func (_mock *MockVersion) GetDate() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVersion_GetDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDate'
type MockVersion_GetDate_Call struct {
	*mock.Call
}

// GetDate is a helper method to define mock.On call
func (_e *MockVersion_Expecter) GetDate() *MockVersion_GetDate_Call {
	return &MockVersion_GetDate_Call{Call: _e.mock.On("GetDate")}
}

func (_c *MockVersion_GetDate_Call) Run(run func()) *MockVersion_GetDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersion_GetDate_Call) Return(s string) *MockVersion_GetDate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVersion_GetDate_Call) RunAndReturn(run func() string) *MockVersion_GetDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockVersion
func (_mock *MockVersion) GetVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVersion_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockVersion_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockVersion_Expecter) GetVersion() *MockVersion_GetVersion_Call {
	return &MockVersion_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockVersion_GetVersion_Call) Run(run func()) *MockVersion_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersion_GetVersion_Call) Return(s string) *MockVersion_GetVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVersion_GetVersion_Call) RunAndReturn(run func() string) *MockVersion_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsDevelopment provides a mock function for the type MockVersion
func (_mock *MockVersion) IsDevelopment() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDevelopment")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockVersion_IsDevelopment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDevelopment'
type MockVersion_IsDevelopment_Call struct {
	*mock.Call
}

// IsDevelopment is a helper method to define mock.On call
func (_e *MockVersion_Expecter) IsDevelopment() *MockVersion_IsDevelopment_Call {
	return &MockVersion_IsDevelopment_Call{Call: _e.mock.On("IsDevelopment")}
}

func (_c *MockVersion_IsDevelopment_Call) Run(run func()) *MockVersion_IsDevelopment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersion_IsDevelopment_Call) Return(b bool) *MockVersion_IsDevelopment_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockVersion_IsDevelopment_Call) RunAndReturn(run func() bool) *MockVersion_IsDevelopment_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockVersion
func (_mock *MockVersion) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockVersion_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockVersion_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockVersion_Expecter) String() *MockVersion_String_Call {
	return &MockVersion_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockVersion_String_Call) Run(run func()) *MockVersion_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersion_String_Call) Return(s string) *MockVersion_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockVersion_String_Call) RunAndReturn(run func() string) *MockVersion_String_Call {
	_c.Call.Return(run)
	return _c
}
