// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"io/fs"

	"github.com/phpboyscout/gtb/pkg/props"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssets creates a new instance of MockAssets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssets(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssets {
	mock := &MockAssets{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssets is an autogenerated mock type for the Assets type
type MockAssets struct {
	mock.Mock
}

type MockAssets_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssets) EXPECT() *MockAssets_Expecter {
	return &MockAssets_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type MockAssets
func (_mock *MockAssets) Exists(name string) (fs.FS, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 fs.FS
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FS, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FS); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssets_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockAssets_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - name string
func (_e *MockAssets_Expecter) Exists(name interface{}) *MockAssets_Exists_Call {
	return &MockAssets_Exists_Call{Call: _e.mock.On("Exists", name)}
}

func (_c *MockAssets_Exists_Call) Run(run func(name string)) *MockAssets_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_Exists_Call) Return(fS fs.FS, err error) *MockAssets_Exists_Call {
	_c.Call.Return(fS, err)
	return _c
}

func (_c *MockAssets_Exists_Call) RunAndReturn(run func(name string) (fs.FS, error)) *MockAssets_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// For provides a mock function for the type MockAssets
func (_mock *MockAssets) For(names ...string) props.Assets {
	var tmpRet mock.Arguments
	if len(names) > 0 {
		tmpRet = _mock.Called(names)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for For")
	}

	var r0 props.Assets
	if returnFunc, ok := ret.Get(0).(func(...string) props.Assets); ok {
		r0 = returnFunc(names...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(props.Assets)
		}
	}
	return r0
}

// MockAssets_For_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'For'
type MockAssets_For_Call struct {
	*mock.Call
}

// For is a helper method to define mock.On call
//   - names ...string
func (_e *MockAssets_Expecter) For(names ...interface{}) *MockAssets_For_Call {
	return &MockAssets_For_Call{Call: _e.mock.On("For",
		append([]interface{}{}, names...)...)}
}

func (_c *MockAssets_For_Call) Run(run func(names ...string)) *MockAssets_For_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAssets_For_Call) Return(assets props.Assets) *MockAssets_For_Call {
	_c.Call.Return(assets)
	return _c
}

func (_c *MockAssets_For_Call) RunAndReturn(run func(names ...string) props.Assets) *MockAssets_For_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAssets
func (_mock *MockAssets) Get(name string) fs.FS {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 fs.FS
	if returnFunc, ok := ret.Get(0).(func(string) fs.FS); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FS)
		}
	}
	return r0
}

// MockAssets_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAssets_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockAssets_Expecter) Get(name interface{}) *MockAssets_Get_Call {
	return &MockAssets_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockAssets_Get_Call) Run(run func(name string)) *MockAssets_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_Get_Call) Return(fS fs.FS) *MockAssets_Get_Call {
	_c.Call.Return(fS)
	return _c
}

func (_c *MockAssets_Get_Call) RunAndReturn(run func(name string) fs.FS) *MockAssets_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Glob provides a mock function for the type MockAssets
func (_mock *MockAssets) Glob(pattern string) ([]string, error) {
	ret := _mock.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for Glob")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(pattern)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pattern)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssets_Glob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Glob'
type MockAssets_Glob_Call struct {
	*mock.Call
}

// Glob is a helper method to define mock.On call
//   - pattern string
func (_e *MockAssets_Expecter) Glob(pattern interface{}) *MockAssets_Glob_Call {
	return &MockAssets_Glob_Call{Call: _e.mock.On("Glob", pattern)}
}

func (_c *MockAssets_Glob_Call) Run(run func(pattern string)) *MockAssets_Glob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_Glob_Call) Return(strings []string, err error) *MockAssets_Glob_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAssets_Glob_Call) RunAndReturn(run func(pattern string) ([]string, error)) *MockAssets_Glob_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function for the type MockAssets
func (_mock *MockAssets) Merge(others ...props.Assets) props.Assets {
	var tmpRet mock.Arguments
	if len(others) > 0 {
		tmpRet = _mock.Called(others)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 props.Assets
	if returnFunc, ok := ret.Get(0).(func(...props.Assets) props.Assets); ok {
		r0 = returnFunc(others...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(props.Assets)
		}
	}
	return r0
}

// MockAssets_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockAssets_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - others ...props.Assets
func (_e *MockAssets_Expecter) Merge(others ...interface{}) *MockAssets_Merge_Call {
	return &MockAssets_Merge_Call{Call: _e.mock.On("Merge",
		append([]interface{}{}, others...)...)}
}

func (_c *MockAssets_Merge_Call) Run(run func(others ...props.Assets)) *MockAssets_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []props.Assets
		var variadicArgs []props.Assets
		if len(args) > 0 {
			variadicArgs = args[0].([]props.Assets)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAssets_Merge_Call) Return(assets props.Assets) *MockAssets_Merge_Call {
	_c.Call.Return(assets)
	return _c
}

func (_c *MockAssets_Merge_Call) RunAndReturn(run func(others ...props.Assets) props.Assets) *MockAssets_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Mount provides a mock function for the type MockAssets
func (_mock *MockAssets) Mount(f fs.FS, prefix string) {
	_mock.Called(f, prefix)
	return
}

// MockAssets_Mount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mount'
type MockAssets_Mount_Call struct {
	*mock.Call
}

// Mount is a helper method to define mock.On call
//   - f fs.FS
//   - prefix string
func (_e *MockAssets_Expecter) Mount(f interface{}, prefix interface{}) *MockAssets_Mount_Call {
	return &MockAssets_Mount_Call{Call: _e.mock.On("Mount", f, prefix)}
}

func (_c *MockAssets_Mount_Call) Run(run func(f fs.FS, prefix string)) *MockAssets_Mount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fs.FS
		if args[0] != nil {
			arg0 = args[0].(fs.FS)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssets_Mount_Call) Return() *MockAssets_Mount_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAssets_Mount_Call) RunAndReturn(run func(f fs.FS, prefix string)) *MockAssets_Mount_Call {
	_c.Run(run)
	return _c
}

// Names provides a mock function for the type MockAssets
func (_mock *MockAssets) Names() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Names")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockAssets_Names_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Names'
type MockAssets_Names_Call struct {
	*mock.Call
}

// Names is a helper method to define mock.On call
func (_e *MockAssets_Expecter) Names() *MockAssets_Names_Call {
	return &MockAssets_Names_Call{Call: _e.mock.On("Names")}
}

func (_c *MockAssets_Names_Call) Run(run func()) *MockAssets_Names_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAssets_Names_Call) Return(strings []string) *MockAssets_Names_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockAssets_Names_Call) RunAndReturn(run func() []string) *MockAssets_Names_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockAssets
func (_mock *MockAssets) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssets_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockAssets_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockAssets_Expecter) Open(name interface{}) *MockAssets_Open_Call {
	return &MockAssets_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockAssets_Open_Call) Run(run func(name string)) *MockAssets_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_Open_Call) Return(file fs.File, err error) *MockAssets_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockAssets_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockAssets_Open_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function for the type MockAssets
func (_mock *MockAssets) ReadDir(name string) ([]fs.DirEntry, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.DirEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]fs.DirEntry, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []fs.DirEntry); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.DirEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssets_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type MockAssets_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - name string
func (_e *MockAssets_Expecter) ReadDir(name interface{}) *MockAssets_ReadDir_Call {
	return &MockAssets_ReadDir_Call{Call: _e.mock.On("ReadDir", name)}
}

func (_c *MockAssets_ReadDir_Call) Run(run func(name string)) *MockAssets_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_ReadDir_Call) Return(dirEntrys []fs.DirEntry, err error) *MockAssets_ReadDir_Call {
	_c.Call.Return(dirEntrys, err)
	return _c
}

func (_c *MockAssets_ReadDir_Call) RunAndReturn(run func(name string) ([]fs.DirEntry, error)) *MockAssets_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAssets
func (_mock *MockAssets) Register(name string, fs1 fs.FS) {
	_mock.Called(name, fs1)
	return
}

// MockAssets_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAssets_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - fs1 fs.FS
func (_e *MockAssets_Expecter) Register(name interface{}, fs1 interface{}) *MockAssets_Register_Call {
	return &MockAssets_Register_Call{Call: _e.mock.On("Register", name, fs1)}
}

func (_c *MockAssets_Register_Call) Run(run func(name string, fs1 fs.FS)) *MockAssets_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 fs.FS
		if args[1] != nil {
			arg1 = args[1].(fs.FS)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAssets_Register_Call) Return() *MockAssets_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAssets_Register_Call) RunAndReturn(run func(name string, fs1 fs.FS)) *MockAssets_Register_Call {
	_c.Run(run)
	return _c
}

// Slice provides a mock function for the type MockAssets
func (_mock *MockAssets) Slice() []fs.FS {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 []fs.FS
	if returnFunc, ok := ret.Get(0).(func() []fs.FS); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.FS)
		}
	}
	return r0
}

// MockAssets_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type MockAssets_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
func (_e *MockAssets_Expecter) Slice() *MockAssets_Slice_Call {
	return &MockAssets_Slice_Call{Call: _e.mock.On("Slice")}
}

func (_c *MockAssets_Slice_Call) Run(run func()) *MockAssets_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAssets_Slice_Call) Return(fSs []fs.FS) *MockAssets_Slice_Call {
	_c.Call.Return(fSs)
	return _c
}

func (_c *MockAssets_Slice_Call) RunAndReturn(run func() []fs.FS) *MockAssets_Slice_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockAssets
func (_mock *MockAssets) Stat(name string) (fs.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAssets_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockAssets_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name string
func (_e *MockAssets_Expecter) Stat(name interface{}) *MockAssets_Stat_Call {
	return &MockAssets_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockAssets_Stat_Call) Run(run func(name string)) *MockAssets_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAssets_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockAssets_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockAssets_Stat_Call) RunAndReturn(run func(name string) (fs.FileInfo, error)) *MockAssets_Stat_Call {
	_c.Call.Return(run)
	return _c
}
