// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"os"

	"github.com/phpboyscout/gtb/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChannelProvider creates a new instance of MockChannelProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelProvider {
	mock := &MockChannelProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChannelProvider is an autogenerated mock type for the ChannelProvider type
type MockChannelProvider struct {
	mock.Mock
}

type MockChannelProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelProvider) EXPECT() *MockChannelProvider_Expecter {
	return &MockChannelProvider_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function for the type MockChannelProvider
func (_mock *MockChannelProvider) Errors() chan error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 chan error
	if returnFunc, ok := ret.Get(0).(func() chan error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}
	return r0
}

// MockChannelProvider_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockChannelProvider_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *MockChannelProvider_Expecter) Errors() *MockChannelProvider_Errors_Call {
	return &MockChannelProvider_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *MockChannelProvider_Errors_Call) Run(run func()) *MockChannelProvider_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelProvider_Errors_Call) Return(errCh chan error) *MockChannelProvider_Errors_Call {
	_c.Call.Return(errCh)
	return _c
}

func (_c *MockChannelProvider_Errors_Call) RunAndReturn(run func() chan error) *MockChannelProvider_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockChannelProvider
func (_mock *MockChannelProvider) Health() chan controls.HealthMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 chan controls.HealthMessage
	if returnFunc, ok := ret.Get(0).(func() chan controls.HealthMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan controls.HealthMessage)
		}
	}
	return r0
}

// MockChannelProvider_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockChannelProvider_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockChannelProvider_Expecter) Health() *MockChannelProvider_Health_Call {
	return &MockChannelProvider_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockChannelProvider_Health_Call) Run(run func()) *MockChannelProvider_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelProvider_Health_Call) Return(healthMessageCh chan controls.HealthMessage) *MockChannelProvider_Health_Call {
	_c.Call.Return(healthMessageCh)
	return _c
}

func (_c *MockChannelProvider_Health_Call) RunAndReturn(run func() chan controls.HealthMessage) *MockChannelProvider_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function for the type MockChannelProvider
func (_mock *MockChannelProvider) Messages() chan controls.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 chan controls.Message
	if returnFunc, ok := ret.Get(0).(func() chan controls.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan controls.Message)
		}
	}
	return r0
}

// MockChannelProvider_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type MockChannelProvider_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *MockChannelProvider_Expecter) Messages() *MockChannelProvider_Messages_Call {
	return &MockChannelProvider_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *MockChannelProvider_Messages_Call) Run(run func()) *MockChannelProvider_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelProvider_Messages_Call) Return(messageCh chan controls.Message) *MockChannelProvider_Messages_Call {
	_c.Call.Return(messageCh)
	return _c
}

func (_c *MockChannelProvider_Messages_Call) RunAndReturn(run func() chan controls.Message) *MockChannelProvider_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Signals provides a mock function for the type MockChannelProvider
func (_mock *MockChannelProvider) Signals() chan os.Signal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Signals")
	}

	var r0 chan os.Signal
	if returnFunc, ok := ret.Get(0).(func() chan os.Signal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan os.Signal)
		}
	}
	return r0
}

// MockChannelProvider_Signals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signals'
type MockChannelProvider_Signals_Call struct {
	*mock.Call
}

// Signals is a helper method to define mock.On call
func (_e *MockChannelProvider_Expecter) Signals() *MockChannelProvider_Signals_Call {
	return &MockChannelProvider_Signals_Call{Call: _e.mock.On("Signals")}
}

func (_c *MockChannelProvider_Signals_Call) Run(run func()) *MockChannelProvider_Signals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChannelProvider_Signals_Call) Return(signalCh chan os.Signal) *MockChannelProvider_Signals_Call {
	_c.Call.Return(signalCh)
	return _c
}

func (_c *MockChannelProvider_Signals_Call) RunAndReturn(run func() chan os.Signal) *MockChannelProvider_Signals_Call {
	_c.Call.Return(run)
	return _c
}
