// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"os"
	"sync"
	"time"

	"github.com/phpboyscout/go-tool-base/pkg/controls"
	"github.com/phpboyscout/go-tool-base/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigurable creates a new instance of MockConfigurable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurable {
	mock := &MockConfigurable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigurable is an autogenerated mock type for the Configurable type
type MockConfigurable struct {
	mock.Mock
}

type MockConfigurable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurable) EXPECT() *MockConfigurable_Expecter {
	return &MockConfigurable_Expecter{mock: &_m.Mock}
}

// SetErrorsChannel provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetErrorsChannel(errs chan error) {
	_mock.Called(errs)
	return
}

// MockConfigurable_SetErrorsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetErrorsChannel'
type MockConfigurable_SetErrorsChannel_Call struct {
	*mock.Call
}

// SetErrorsChannel is a helper method to define mock.On call
//   - errs chan error
func (_e *MockConfigurable_Expecter) SetErrorsChannel(errs interface{}) *MockConfigurable_SetErrorsChannel_Call {
	return &MockConfigurable_SetErrorsChannel_Call{Call: _e.mock.On("SetErrorsChannel", errs)}
}

func (_c *MockConfigurable_SetErrorsChannel_Call) Run(run func(errs chan error)) *MockConfigurable_SetErrorsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan error
		if args[0] != nil {
			arg0 = args[0].(chan error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetErrorsChannel_Call) Return() *MockConfigurable_SetErrorsChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetErrorsChannel_Call) RunAndReturn(run func(errs chan error)) *MockConfigurable_SetErrorsChannel_Call {
	_c.Run(run)
	return _c
}

// SetHealthChannel provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetHealthChannel(health chan controls.HealthMessage) {
	_mock.Called(health)
	return
}

// MockConfigurable_SetHealthChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHealthChannel'
type MockConfigurable_SetHealthChannel_Call struct {
	*mock.Call
}

// SetHealthChannel is a helper method to define mock.On call
//   - health chan controls.HealthMessage
func (_e *MockConfigurable_Expecter) SetHealthChannel(health interface{}) *MockConfigurable_SetHealthChannel_Call {
	return &MockConfigurable_SetHealthChannel_Call{Call: _e.mock.On("SetHealthChannel", health)}
}

func (_c *MockConfigurable_SetHealthChannel_Call) Run(run func(health chan controls.HealthMessage)) *MockConfigurable_SetHealthChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan controls.HealthMessage
		if args[0] != nil {
			arg0 = args[0].(chan controls.HealthMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetHealthChannel_Call) Return() *MockConfigurable_SetHealthChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetHealthChannel_Call) RunAndReturn(run func(health chan controls.HealthMessage)) *MockConfigurable_SetHealthChannel_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetLogger(l logger.Logger) {
	_mock.Called(l)
	return
}

// MockConfigurable_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockConfigurable_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - l logger.Logger
func (_e *MockConfigurable_Expecter) SetLogger(l interface{}) *MockConfigurable_SetLogger_Call {
	return &MockConfigurable_SetLogger_Call{Call: _e.mock.On("SetLogger", l)}
}

func (_c *MockConfigurable_SetLogger_Call) Run(run func(l logger.Logger)) *MockConfigurable_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Logger
		if args[0] != nil {
			arg0 = args[0].(logger.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetLogger_Call) Return() *MockConfigurable_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetLogger_Call) RunAndReturn(run func(l logger.Logger)) *MockConfigurable_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetMessageChannel provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetMessageChannel(control chan controls.Message) {
	_mock.Called(control)
	return
}

// MockConfigurable_SetMessageChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessageChannel'
type MockConfigurable_SetMessageChannel_Call struct {
	*mock.Call
}

// SetMessageChannel is a helper method to define mock.On call
//   - control chan controls.Message
func (_e *MockConfigurable_Expecter) SetMessageChannel(control interface{}) *MockConfigurable_SetMessageChannel_Call {
	return &MockConfigurable_SetMessageChannel_Call{Call: _e.mock.On("SetMessageChannel", control)}
}

func (_c *MockConfigurable_SetMessageChannel_Call) Run(run func(control chan controls.Message)) *MockConfigurable_SetMessageChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan controls.Message
		if args[0] != nil {
			arg0 = args[0].(chan controls.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetMessageChannel_Call) Return() *MockConfigurable_SetMessageChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetMessageChannel_Call) RunAndReturn(run func(control chan controls.Message)) *MockConfigurable_SetMessageChannel_Call {
	_c.Run(run)
	return _c
}

// SetShutdownTimeout provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetShutdownTimeout(d time.Duration) {
	_mock.Called(d)
	return
}

// MockConfigurable_SetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShutdownTimeout'
type MockConfigurable_SetShutdownTimeout_Call struct {
	*mock.Call
}

// SetShutdownTimeout is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockConfigurable_Expecter) SetShutdownTimeout(d interface{}) *MockConfigurable_SetShutdownTimeout_Call {
	return &MockConfigurable_SetShutdownTimeout_Call{Call: _e.mock.On("SetShutdownTimeout", d)}
}

func (_c *MockConfigurable_SetShutdownTimeout_Call) Run(run func(d time.Duration)) *MockConfigurable_SetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetShutdownTimeout_Call) Return() *MockConfigurable_SetShutdownTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetShutdownTimeout_Call) RunAndReturn(run func(d time.Duration)) *MockConfigurable_SetShutdownTimeout_Call {
	_c.Run(run)
	return _c
}

// SetSignalsChannel provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetSignalsChannel(sigs chan os.Signal) {
	_mock.Called(sigs)
	return
}

// MockConfigurable_SetSignalsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSignalsChannel'
type MockConfigurable_SetSignalsChannel_Call struct {
	*mock.Call
}

// SetSignalsChannel is a helper method to define mock.On call
//   - sigs chan os.Signal
func (_e *MockConfigurable_Expecter) SetSignalsChannel(sigs interface{}) *MockConfigurable_SetSignalsChannel_Call {
	return &MockConfigurable_SetSignalsChannel_Call{Call: _e.mock.On("SetSignalsChannel", sigs)}
}

func (_c *MockConfigurable_SetSignalsChannel_Call) Run(run func(sigs chan os.Signal)) *MockConfigurable_SetSignalsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan os.Signal
		if args[0] != nil {
			arg0 = args[0].(chan os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetSignalsChannel_Call) Return() *MockConfigurable_SetSignalsChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetSignalsChannel_Call) RunAndReturn(run func(sigs chan os.Signal)) *MockConfigurable_SetSignalsChannel_Call {
	_c.Run(run)
	return _c
}

// SetWaitGroup provides a mock function for the type MockConfigurable
func (_mock *MockConfigurable) SetWaitGroup(wg *sync.WaitGroup) {
	_mock.Called(wg)
	return
}

// MockConfigurable_SetWaitGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaitGroup'
type MockConfigurable_SetWaitGroup_Call struct {
	*mock.Call
}

// SetWaitGroup is a helper method to define mock.On call
//   - wg *sync.WaitGroup
func (_e *MockConfigurable_Expecter) SetWaitGroup(wg interface{}) *MockConfigurable_SetWaitGroup_Call {
	return &MockConfigurable_SetWaitGroup_Call{Call: _e.mock.On("SetWaitGroup", wg)}
}

func (_c *MockConfigurable_SetWaitGroup_Call) Run(run func(wg *sync.WaitGroup)) *MockConfigurable_SetWaitGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sync.WaitGroup
		if args[0] != nil {
			arg0 = args[0].(*sync.WaitGroup)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockConfigurable_SetWaitGroup_Call) Return() *MockConfigurable_SetWaitGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConfigurable_SetWaitGroup_Call) RunAndReturn(run func(wg *sync.WaitGroup)) *MockConfigurable_SetWaitGroup_Call {
	_c.Run(run)
	return _c
}
