// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"github.com/phpboyscout/go-tool-base/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthReporter creates a new instance of MockHealthReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthReporter {
	mock := &MockHealthReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthReporter is an autogenerated mock type for the HealthReporter type
type MockHealthReporter struct {
	mock.Mock
}

type MockHealthReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthReporter) EXPECT() *MockHealthReporter_Expecter {
	return &MockHealthReporter_Expecter{mock: &_m.Mock}
}

// GetServiceInfo provides a mock function for the type MockHealthReporter
func (_mock *MockHealthReporter) GetServiceInfo(name string) (controls.ServiceInfo, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceInfo")
	}

	var r0 controls.ServiceInfo
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (controls.ServiceInfo, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controls.ServiceInfo); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(controls.ServiceInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockHealthReporter_GetServiceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceInfo'
type MockHealthReporter_GetServiceInfo_Call struct {
	*mock.Call
}

// GetServiceInfo is a helper method to define mock.On call
//   - name string
func (_e *MockHealthReporter_Expecter) GetServiceInfo(name interface{}) *MockHealthReporter_GetServiceInfo_Call {
	return &MockHealthReporter_GetServiceInfo_Call{Call: _e.mock.On("GetServiceInfo", name)}
}

func (_c *MockHealthReporter_GetServiceInfo_Call) Run(run func(name string)) *MockHealthReporter_GetServiceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthReporter_GetServiceInfo_Call) Return(serviceInfo controls.ServiceInfo, b bool) *MockHealthReporter_GetServiceInfo_Call {
	_c.Call.Return(serviceInfo, b)
	return _c
}

func (_c *MockHealthReporter_GetServiceInfo_Call) RunAndReturn(run func(name string) (controls.ServiceInfo, bool)) *MockHealthReporter_GetServiceInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Liveness provides a mock function for the type MockHealthReporter
func (_mock *MockHealthReporter) Liveness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthReporter_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type MockHealthReporter_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
func (_e *MockHealthReporter_Expecter) Liveness() *MockHealthReporter_Liveness_Call {
	return &MockHealthReporter_Liveness_Call{Call: _e.mock.On("Liveness")}
}

func (_c *MockHealthReporter_Liveness_Call) Run(run func()) *MockHealthReporter_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthReporter_Liveness_Call) Return(healthReport controls.HealthReport) *MockHealthReporter_Liveness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthReporter_Liveness_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthReporter_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function for the type MockHealthReporter
func (_mock *MockHealthReporter) Readiness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthReporter_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type MockHealthReporter_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
func (_e *MockHealthReporter_Expecter) Readiness() *MockHealthReporter_Readiness_Call {
	return &MockHealthReporter_Readiness_Call{Call: _e.mock.On("Readiness")}
}

func (_c *MockHealthReporter_Readiness_Call) Run(run func()) *MockHealthReporter_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthReporter_Readiness_Call) Return(healthReport controls.HealthReport) *MockHealthReporter_Readiness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthReporter_Readiness_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthReporter_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockHealthReporter
func (_mock *MockHealthReporter) Status() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// MockHealthReporter_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockHealthReporter_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockHealthReporter_Expecter) Status() *MockHealthReporter_Status_Call {
	return &MockHealthReporter_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockHealthReporter_Status_Call) Run(run func()) *MockHealthReporter_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthReporter_Status_Call) Return(healthReport controls.HealthReport) *MockHealthReporter_Status_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *MockHealthReporter_Status_Call) RunAndReturn(run func() controls.HealthReport) *MockHealthReporter_Status_Call {
	_c.Call.Return(run)
	return _c
}
