// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"github.com/phpboyscout/gtb/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// IsRunning provides a mock function for the type MockRunner
func (_mock *MockRunner) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRunner_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockRunner_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockRunner_Expecter) IsRunning() *MockRunner_IsRunning_Call {
	return &MockRunner_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockRunner_IsRunning_Call) Run(run func()) *MockRunner_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_IsRunning_Call) Return(b bool) *MockRunner_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRunner_IsRunning_Call) RunAndReturn(run func() bool) *MockRunner_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockRunner
func (_mock *MockRunner) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRunner_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockRunner_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockRunner_Expecter) IsStopped() *MockRunner_IsStopped_Call {
	return &MockRunner_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockRunner_IsStopped_Call) Run(run func()) *MockRunner_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_IsStopped_Call) Return(b bool) *MockRunner_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRunner_IsStopped_Call) RunAndReturn(run func() bool) *MockRunner_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopping provides a mock function for the type MockRunner
func (_mock *MockRunner) IsStopping() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopping")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRunner_IsStopping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopping'
type MockRunner_IsStopping_Call struct {
	*mock.Call
}

// IsStopping is a helper method to define mock.On call
func (_e *MockRunner_Expecter) IsStopping() *MockRunner_IsStopping_Call {
	return &MockRunner_IsStopping_Call{Call: _e.mock.On("IsStopping")}
}

func (_c *MockRunner_IsStopping_Call) Run(run func()) *MockRunner_IsStopping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_IsStopping_Call) Return(b bool) *MockRunner_IsStopping_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRunner_IsStopping_Call) RunAndReturn(run func() bool) *MockRunner_IsStopping_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockRunner
func (_mock *MockRunner) Register(id string, opts ...controls.ServiceOption) {
	if len(opts) > 0 {
		_mock.Called(id, opts)
	} else {
		_mock.Called(id)
	}

	return
}

// MockRunner_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRunner_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - id string
//   - opts ...controls.ServiceOption
func (_e *MockRunner_Expecter) Register(id interface{}, opts ...interface{}) *MockRunner_Register_Call {
	return &MockRunner_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{id}, opts...)...)}
}

func (_c *MockRunner_Register_Call) Run(run func(id string, opts ...controls.ServiceOption)) *MockRunner_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []controls.ServiceOption
		var variadicArgs []controls.ServiceOption
		if len(args) > 1 {
			variadicArgs = args[1].([]controls.ServiceOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRunner_Register_Call) Return() *MockRunner_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRunner_Register_Call) RunAndReturn(run func(id string, opts ...controls.ServiceOption)) *MockRunner_Register_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockRunner
func (_mock *MockRunner) Start() {
	_mock.Called()
	return
}

// MockRunner_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockRunner_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockRunner_Expecter) Start() *MockRunner_Start_Call {
	return &MockRunner_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockRunner_Start_Call) Run(run func()) *MockRunner_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_Start_Call) Return() *MockRunner_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRunner_Start_Call) RunAndReturn(run func()) *MockRunner_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockRunner
func (_mock *MockRunner) Stop() {
	_mock.Called()
	return
}

// MockRunner_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRunner_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockRunner_Expecter) Stop() *MockRunner_Stop_Call {
	return &MockRunner_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockRunner_Stop_Call) Run(run func()) *MockRunner_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_Stop_Call) Return() *MockRunner_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRunner_Stop_Call) RunAndReturn(run func()) *MockRunner_Stop_Call {
	_c.Run(run)
	return _c
}
