// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/controls"
	"github.com/phpboyscout/go-tool-base/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStateAccessor creates a new instance of MockStateAccessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateAccessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateAccessor {
	mock := &MockStateAccessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateAccessor is an autogenerated mock type for the StateAccessor type
type MockStateAccessor struct {
	mock.Mock
}

type MockStateAccessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateAccessor) EXPECT() *MockStateAccessor_Expecter {
	return &MockStateAccessor_Expecter{mock: &_m.Mock}
}

// GetContext provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockStateAccessor_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockStateAccessor_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) GetContext() *MockStateAccessor_GetContext_Call {
	return &MockStateAccessor_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockStateAccessor_GetContext_Call) Run(run func()) *MockStateAccessor_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_GetContext_Call) Return(context1 context.Context) *MockStateAccessor_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockStateAccessor_GetContext_Call) RunAndReturn(run func() context.Context) *MockStateAccessor_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) GetLogger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockStateAccessor_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockStateAccessor_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) GetLogger() *MockStateAccessor_GetLogger_Call {
	return &MockStateAccessor_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockStateAccessor_GetLogger_Call) Run(run func()) *MockStateAccessor_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_GetLogger_Call) Return(logger1 logger.Logger) *MockStateAccessor_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockStateAccessor_GetLogger_Call) RunAndReturn(run func() logger.Logger) *MockStateAccessor_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) GetState() controls.State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 controls.State
	if returnFunc, ok := ret.Get(0).(func() controls.State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.State)
	}
	return r0
}

// MockStateAccessor_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockStateAccessor_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *MockStateAccessor_Expecter) GetState() *MockStateAccessor_GetState_Call {
	return &MockStateAccessor_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *MockStateAccessor_GetState_Call) Run(run func()) *MockStateAccessor_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateAccessor_GetState_Call) Return(state controls.State) *MockStateAccessor_GetState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockStateAccessor_GetState_Call) RunAndReturn(run func() controls.State) *MockStateAccessor_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function for the type MockStateAccessor
func (_mock *MockStateAccessor) SetState(state controls.State) {
	_mock.Called(state)
	return
}

// MockStateAccessor_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockStateAccessor_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - state controls.State
func (_e *MockStateAccessor_Expecter) SetState(state interface{}) *MockStateAccessor_SetState_Call {
	return &MockStateAccessor_SetState_Call{Call: _e.mock.On("SetState", state)}
}

func (_c *MockStateAccessor_SetState_Call) Run(run func(state controls.State)) *MockStateAccessor_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 controls.State
		if args[0] != nil {
			arg0 = args[0].(controls.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStateAccessor_SetState_Call) Return() *MockStateAccessor_SetState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStateAccessor_SetState_Call) RunAndReturn(run func(state controls.State)) *MockStateAccessor_SetState_Call {
	_c.Run(run)
	return _c
}
