// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setup

import (
	"github.com/phpboyscout/gtb/pkg/config"
	"github.com/phpboyscout/gtb/pkg/props"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInitialiser creates a new instance of MockInitialiser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInitialiser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInitialiser {
	mock := &MockInitialiser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInitialiser is an autogenerated mock type for the Initialiser type
type MockInitialiser struct {
	mock.Mock
}

type MockInitialiser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInitialiser) EXPECT() *MockInitialiser_Expecter {
	return &MockInitialiser_Expecter{mock: &_m.Mock}
}

// Configure provides a mock function for the type MockInitialiser
func (_mock *MockInitialiser) Configure(p *props.Props, cfg config.Containable) error {
	ret := _mock.Called(p, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Configure")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*props.Props, config.Containable) error); ok {
		r0 = returnFunc(p, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInitialiser_Configure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Configure'
type MockInitialiser_Configure_Call struct {
	*mock.Call
}

// Configure is a helper method to define mock.On call
//   - p *props.Props
//   - cfg config.Containable
func (_e *MockInitialiser_Expecter) Configure(p interface{}, cfg interface{}) *MockInitialiser_Configure_Call {
	return &MockInitialiser_Configure_Call{Call: _e.mock.On("Configure", p, cfg)}
}

func (_c *MockInitialiser_Configure_Call) Run(run func(p *props.Props, cfg config.Containable)) *MockInitialiser_Configure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *props.Props
		if args[0] != nil {
			arg0 = args[0].(*props.Props)
		}
		var arg1 config.Containable
		if args[1] != nil {
			arg1 = args[1].(config.Containable)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInitialiser_Configure_Call) Return(err error) *MockInitialiser_Configure_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInitialiser_Configure_Call) RunAndReturn(run func(p *props.Props, cfg config.Containable) error) *MockInitialiser_Configure_Call {
	_c.Call.Return(run)
	return _c
}

// IsConfigured provides a mock function for the type MockInitialiser
func (_mock *MockInitialiser) IsConfigured(cfg config.Containable) bool {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for IsConfigured")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(config.Containable) bool); ok {
		r0 = returnFunc(cfg)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockInitialiser_IsConfigured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConfigured'
type MockInitialiser_IsConfigured_Call struct {
	*mock.Call
}

// IsConfigured is a helper method to define mock.On call
//   - cfg config.Containable
func (_e *MockInitialiser_Expecter) IsConfigured(cfg interface{}) *MockInitialiser_IsConfigured_Call {
	return &MockInitialiser_IsConfigured_Call{Call: _e.mock.On("IsConfigured", cfg)}
}

func (_c *MockInitialiser_IsConfigured_Call) Run(run func(cfg config.Containable)) *MockInitialiser_IsConfigured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Containable
		if args[0] != nil {
			arg0 = args[0].(config.Containable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInitialiser_IsConfigured_Call) Return(b bool) *MockInitialiser_IsConfigured_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockInitialiser_IsConfigured_Call) RunAndReturn(run func(cfg config.Containable) bool) *MockInitialiser_IsConfigured_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockInitialiser
func (_mock *MockInitialiser) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockInitialiser_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockInitialiser_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockInitialiser_Expecter) Name() *MockInitialiser_Name_Call {
	return &MockInitialiser_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockInitialiser_Name_Call) Run(run func()) *MockInitialiser_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInitialiser_Name_Call) Return(s string) *MockInitialiser_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockInitialiser_Name_Call) RunAndReturn(run func() string) *MockInitialiser_Name_Call {
	_c.Call.Return(run)
	return _c
}
