// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errorhandling

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHelpConfig creates a new instance of MockHelpConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHelpConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHelpConfig {
	mock := &MockHelpConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHelpConfig is an autogenerated mock type for the HelpConfig type
type MockHelpConfig struct {
	mock.Mock
}

type MockHelpConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHelpConfig) EXPECT() *MockHelpConfig_Expecter {
	return &MockHelpConfig_Expecter{mock: &_m.Mock}
}

// SupportMessage provides a mock function for the type MockHelpConfig
func (_mock *MockHelpConfig) SupportMessage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHelpConfig_SupportMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportMessage'
type MockHelpConfig_SupportMessage_Call struct {
	*mock.Call
}

// SupportMessage is a helper method to define mock.On call
func (_e *MockHelpConfig_Expecter) SupportMessage() *MockHelpConfig_SupportMessage_Call {
	return &MockHelpConfig_SupportMessage_Call{Call: _e.mock.On("SupportMessage")}
}

func (_c *MockHelpConfig_SupportMessage_Call) Run(run func()) *MockHelpConfig_SupportMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHelpConfig_SupportMessage_Call) Return(s string) *MockHelpConfig_SupportMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHelpConfig_SupportMessage_Call) RunAndReturn(run func() string) *MockHelpConfig_SupportMessage_Call {
	_c.Call.Return(run)
	return _c
}
