// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config

import (
	"github.com/phpboyscout/gtb/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObservable creates a new instance of MockObservable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservable {
	mock := &MockObservable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObservable is an autogenerated mock type for the Observable type
type MockObservable struct {
	mock.Mock
}

type MockObservable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservable) EXPECT() *MockObservable_Expecter {
	return &MockObservable_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockObservable
func (_mock *MockObservable) Run(containable config.Containable, errCh chan error) {
	_mock.Called(containable, errCh)
	return
}

// MockObservable_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockObservable_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - containable config.Containable
//   - errCh chan error
func (_e *MockObservable_Expecter) Run(containable interface{}, errCh interface{}) *MockObservable_Run_Call {
	return &MockObservable_Run_Call{Call: _e.mock.On("Run", containable, errCh)}
}

func (_c *MockObservable_Run_Call) Run(run func(containable config.Containable, errCh chan error)) *MockObservable_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Containable
		if args[0] != nil {
			arg0 = args[0].(config.Containable)
		}
		var arg1 chan error
		if args[1] != nil {
			arg1 = args[1].(chan error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObservable_Run_Call) Return() *MockObservable_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObservable_Run_Call) RunAndReturn(run func(containable config.Containable, errCh chan error)) *MockObservable_Run_Call {
	_c.Run(run)
	return _c
}
