// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"context"

	"github.com/phpboyscout/go-tool-base/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// newMockhealthSource creates a new instance of mockhealthSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhealthSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhealthSource {
	mock := &mockhealthSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhealthSource is an autogenerated mock type for the healthSource type
type mockhealthSource struct {
	mock.Mock
}

type mockhealthSource_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhealthSource) EXPECT() *mockhealthSource_Expecter {
	return &mockhealthSource_Expecter{mock: &_m.Mock}
}

// GetContext provides a mock function for the type mockhealthSource
func (_mock *mockhealthSource) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// mockhealthSource_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type mockhealthSource_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *mockhealthSource_Expecter) GetContext() *mockhealthSource_GetContext_Call {
	return &mockhealthSource_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *mockhealthSource_GetContext_Call) Run(run func()) *mockhealthSource_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthSource_GetContext_Call) Return(context1 context.Context) *mockhealthSource_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *mockhealthSource_GetContext_Call) RunAndReturn(run func() context.Context) *mockhealthSource_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceInfo provides a mock function for the type mockhealthSource
func (_mock *mockhealthSource) GetServiceInfo(name string) (controls.ServiceInfo, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceInfo")
	}

	var r0 controls.ServiceInfo
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (controls.ServiceInfo, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) controls.ServiceInfo); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(controls.ServiceInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// mockhealthSource_GetServiceInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceInfo'
type mockhealthSource_GetServiceInfo_Call struct {
	*mock.Call
}

// GetServiceInfo is a helper method to define mock.On call
//   - name string
func (_e *mockhealthSource_Expecter) GetServiceInfo(name interface{}) *mockhealthSource_GetServiceInfo_Call {
	return &mockhealthSource_GetServiceInfo_Call{Call: _e.mock.On("GetServiceInfo", name)}
}

func (_c *mockhealthSource_GetServiceInfo_Call) Run(run func(name string)) *mockhealthSource_GetServiceInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhealthSource_GetServiceInfo_Call) Return(serviceInfo controls.ServiceInfo, b bool) *mockhealthSource_GetServiceInfo_Call {
	_c.Call.Return(serviceInfo, b)
	return _c
}

func (_c *mockhealthSource_GetServiceInfo_Call) RunAndReturn(run func(name string) (controls.ServiceInfo, bool)) *mockhealthSource_GetServiceInfo_Call {
	_c.Call.Return(run)
	return _c
}

// Liveness provides a mock function for the type mockhealthSource
func (_mock *mockhealthSource) Liveness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Liveness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// mockhealthSource_Liveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Liveness'
type mockhealthSource_Liveness_Call struct {
	*mock.Call
}

// Liveness is a helper method to define mock.On call
func (_e *mockhealthSource_Expecter) Liveness() *mockhealthSource_Liveness_Call {
	return &mockhealthSource_Liveness_Call{Call: _e.mock.On("Liveness")}
}

func (_c *mockhealthSource_Liveness_Call) Run(run func()) *mockhealthSource_Liveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthSource_Liveness_Call) Return(healthReport controls.HealthReport) *mockhealthSource_Liveness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *mockhealthSource_Liveness_Call) RunAndReturn(run func() controls.HealthReport) *mockhealthSource_Liveness_Call {
	_c.Call.Return(run)
	return _c
}

// Readiness provides a mock function for the type mockhealthSource
func (_mock *mockhealthSource) Readiness() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Readiness")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// mockhealthSource_Readiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Readiness'
type mockhealthSource_Readiness_Call struct {
	*mock.Call
}

// Readiness is a helper method to define mock.On call
func (_e *mockhealthSource_Expecter) Readiness() *mockhealthSource_Readiness_Call {
	return &mockhealthSource_Readiness_Call{Call: _e.mock.On("Readiness")}
}

func (_c *mockhealthSource_Readiness_Call) Run(run func()) *mockhealthSource_Readiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthSource_Readiness_Call) Return(healthReport controls.HealthReport) *mockhealthSource_Readiness_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *mockhealthSource_Readiness_Call) RunAndReturn(run func() controls.HealthReport) *mockhealthSource_Readiness_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type mockhealthSource
func (_mock *mockhealthSource) Status() controls.HealthReport {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 controls.HealthReport
	if returnFunc, ok := ret.Get(0).(func() controls.HealthReport); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.HealthReport)
	}
	return r0
}

// mockhealthSource_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type mockhealthSource_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *mockhealthSource_Expecter) Status() *mockhealthSource_Status_Call {
	return &mockhealthSource_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *mockhealthSource_Status_Call) Run(run func()) *mockhealthSource_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthSource_Status_Call) Return(healthReport controls.HealthReport) *mockhealthSource_Status_Call {
	_c.Call.Return(healthReport)
	return _c
}

func (_c *mockhealthSource_Status_Call) RunAndReturn(run func() controls.HealthReport) *mockhealthSource_Status_Call {
	_c.Call.Return(run)
	return _c
}
