// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package update

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// GetCurrentVersion provides a mock function for the type MockUpdater
func (_mock *MockUpdater) GetCurrentVersion() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentVersion")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUpdater_GetCurrentVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentVersion'
type MockUpdater_GetCurrentVersion_Call struct {
	*mock.Call
}

// GetCurrentVersion is a helper method to define mock.On call
func (_e *MockUpdater_Expecter) GetCurrentVersion() *MockUpdater_GetCurrentVersion_Call {
	return &MockUpdater_GetCurrentVersion_Call{Call: _e.mock.On("GetCurrentVersion")}
}

func (_c *MockUpdater_GetCurrentVersion_Call) Run(run func()) *MockUpdater_GetCurrentVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdater_GetCurrentVersion_Call) Return(s string) *MockUpdater_GetCurrentVersion_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUpdater_GetCurrentVersion_Call) RunAndReturn(run func() string) *MockUpdater_GetCurrentVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestVersionString provides a mock function for the type MockUpdater
func (_mock *MockUpdater) GetLatestVersionString(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestVersionString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdater_GetLatestVersionString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestVersionString'
type MockUpdater_GetLatestVersionString_Call struct {
	*mock.Call
}

// GetLatestVersionString is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdater_Expecter) GetLatestVersionString(ctx interface{}) *MockUpdater_GetLatestVersionString_Call {
	return &MockUpdater_GetLatestVersionString_Call{Call: _e.mock.On("GetLatestVersionString", ctx)}
}

func (_c *MockUpdater_GetLatestVersionString_Call) Run(run func(ctx context.Context)) *MockUpdater_GetLatestVersionString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdater_GetLatestVersionString_Call) Return(s string, err error) *MockUpdater_GetLatestVersionString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUpdater_GetLatestVersionString_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockUpdater_GetLatestVersionString_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseNotes provides a mock function for the type MockUpdater
func (_mock *MockUpdater) GetReleaseNotes(ctx context.Context, from string, to string) (string, error) {
	ret := _mock.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseNotes")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, from, to)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdater_GetReleaseNotes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseNotes'
type MockUpdater_GetReleaseNotes_Call struct {
	*mock.Call
}

// GetReleaseNotes is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - to string
func (_e *MockUpdater_Expecter) GetReleaseNotes(ctx interface{}, from interface{}, to interface{}) *MockUpdater_GetReleaseNotes_Call {
	return &MockUpdater_GetReleaseNotes_Call{Call: _e.mock.On("GetReleaseNotes", ctx, from, to)}
}

func (_c *MockUpdater_GetReleaseNotes_Call) Run(run func(ctx context.Context, from string, to string)) *MockUpdater_GetReleaseNotes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUpdater_GetReleaseNotes_Call) Return(s string, err error) *MockUpdater_GetReleaseNotes_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUpdater_GetReleaseNotes_Call) RunAndReturn(run func(ctx context.Context, from string, to string) (string, error)) *MockUpdater_GetReleaseNotes_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUpdater
func (_mock *MockUpdater) Update(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUpdater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUpdater_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUpdater_Expecter) Update(ctx interface{}) *MockUpdater_Update_Call {
	return &MockUpdater_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *MockUpdater_Update_Call) Run(run func(ctx context.Context)) *MockUpdater_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUpdater_Update_Call) Return(s string, err error) *MockUpdater_Update_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUpdater_Update_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockUpdater_Update_Call {
	_c.Call.Return(run)
	return _c
}
