// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package logger

import (
	"log/slog"

	"github.com/phpboyscout/go-tool-base/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *MockLogger_Expecter) Debug(msg interface{}, keyvals ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, keyvals ...any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, keyvals ...any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Debugf provides a mock function for the type MockLogger
func (_mock *MockLogger) Debugf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Debugf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debugf'
type MockLogger_Debugf_Call struct {
	*mock.Call
}

// Debugf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Debugf(format interface{}, args ...interface{}) *MockLogger_Debugf_Call {
	return &MockLogger_Debugf_Call{Call: _e.mock.On("Debugf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debugf_Call) Run(run func(format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debugf_Call) Return() *MockLogger_Debugf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debugf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Debugf_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *MockLogger_Expecter) Error(msg interface{}, keyvals ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, keyvals ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, keyvals ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function for the type MockLogger
func (_mock *MockLogger) Errorf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type MockLogger_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Errorf(format interface{}, args ...interface{}) *MockLogger_Errorf_Call {
	return &MockLogger_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Errorf_Call) Run(run func(format string, args ...any)) *MockLogger_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Errorf_Call) Return() *MockLogger_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Errorf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Errorf_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockLogger
func (_mock *MockLogger) Fatal(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *MockLogger_Expecter) Fatal(msg interface{}, keyvals ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(msg string, keyvals ...any)) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(msg string, keyvals ...any)) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Fatalf provides a mock function for the type MockLogger
func (_mock *MockLogger) Fatalf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Fatalf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatalf'
type MockLogger_Fatalf_Call struct {
	*mock.Call
}

// Fatalf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Fatalf(format interface{}, args ...interface{}) *MockLogger_Fatalf_Call {
	return &MockLogger_Fatalf_Call{Call: _e.mock.On("Fatalf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Fatalf_Call) Run(run func(format string, args ...any)) *MockLogger_Fatalf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Fatalf_Call) Return() *MockLogger_Fatalf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatalf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Fatalf_Call {
	_c.Run(run)
	return _c
}

// GetLevel provides a mock function for the type MockLogger
func (_mock *MockLogger) GetLevel() logger.Level {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLevel")
	}

	var r0 logger.Level
	if returnFunc, ok := ret.Get(0).(func() logger.Level); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(logger.Level)
	}
	return r0
}

// MockLogger_GetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLevel'
type MockLogger_GetLevel_Call struct {
	*mock.Call
}

// GetLevel is a helper method to define mock.On call
func (_e *MockLogger_Expecter) GetLevel() *MockLogger_GetLevel_Call {
	return &MockLogger_GetLevel_Call{Call: _e.mock.On("GetLevel")}
}

func (_c *MockLogger_GetLevel_Call) Run(run func()) *MockLogger_GetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_GetLevel_Call) Return(level logger.Level) *MockLogger_GetLevel_Call {
	_c.Call.Return(level)
	return _c
}

func (_c *MockLogger_GetLevel_Call) RunAndReturn(run func() logger.Level) *MockLogger_GetLevel_Call {
	_c.Call.Return(run)
	return _c
}

// Handler provides a mock function for the type MockLogger
func (_mock *MockLogger) Handler() slog.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 slog.Handler
	if returnFunc, ok := ret.Get(0).(func() slog.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(slog.Handler)
		}
	}
	return r0
}

// MockLogger_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockLogger_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockLogger_Expecter) Handler() *MockLogger_Handler_Call {
	return &MockLogger_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *MockLogger_Handler_Call) Run(run func()) *MockLogger_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLogger_Handler_Call) Return(handler slog.Handler) *MockLogger_Handler_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockLogger_Handler_Call) RunAndReturn(run func() slog.Handler) *MockLogger_Handler_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *MockLogger_Expecter) Info(msg interface{}, keyvals ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, keyvals ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, keyvals ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Infof provides a mock function for the type MockLogger
func (_mock *MockLogger) Infof(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Infof_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Infof'
type MockLogger_Infof_Call struct {
	*mock.Call
}

// Infof is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Infof(format interface{}, args ...interface{}) *MockLogger_Infof_Call {
	return &MockLogger_Infof_Call{Call: _e.mock.On("Infof",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Infof_Call) Run(run func(format string, args ...any)) *MockLogger_Infof_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Infof_Call) Return() *MockLogger_Infof_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Infof_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Infof_Call {
	_c.Run(run)
	return _c
}

// Print provides a mock function for the type MockLogger
func (_mock *MockLogger) Print(msg any, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockLogger_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - msg any
//   - keyvals ...any
func (_e *MockLogger_Expecter) Print(msg interface{}, keyvals ...interface{}) *MockLogger_Print_Call {
	return &MockLogger_Print_Call{Call: _e.mock.On("Print",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Print_Call) Run(run func(msg any, keyvals ...any)) *MockLogger_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Print_Call) Return() *MockLogger_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Print_Call) RunAndReturn(run func(msg any, keyvals ...any)) *MockLogger_Print_Call {
	_c.Run(run)
	return _c
}

// SetFormatter provides a mock function for the type MockLogger
func (_mock *MockLogger) SetFormatter(f logger.Formatter) {
	_mock.Called(f)
	return
}

// MockLogger_SetFormatter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFormatter'
type MockLogger_SetFormatter_Call struct {
	*mock.Call
}

// SetFormatter is a helper method to define mock.On call
//   - f logger.Formatter
func (_e *MockLogger_Expecter) SetFormatter(f interface{}) *MockLogger_SetFormatter_Call {
	return &MockLogger_SetFormatter_Call{Call: _e.mock.On("SetFormatter", f)}
}

func (_c *MockLogger_SetFormatter_Call) Run(run func(f logger.Formatter)) *MockLogger_SetFormatter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Formatter
		if args[0] != nil {
			arg0 = args[0].(logger.Formatter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetFormatter_Call) Return() *MockLogger_SetFormatter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetFormatter_Call) RunAndReturn(run func(f logger.Formatter)) *MockLogger_SetFormatter_Call {
	_c.Run(run)
	return _c
}

// SetLevel provides a mock function for the type MockLogger
func (_mock *MockLogger) SetLevel(level logger.Level) {
	_mock.Called(level)
	return
}

// MockLogger_SetLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLevel'
type MockLogger_SetLevel_Call struct {
	*mock.Call
}

// SetLevel is a helper method to define mock.On call
//   - level logger.Level
func (_e *MockLogger_Expecter) SetLevel(level interface{}) *MockLogger_SetLevel_Call {
	return &MockLogger_SetLevel_Call{Call: _e.mock.On("SetLevel", level)}
}

func (_c *MockLogger_SetLevel_Call) Run(run func(level logger.Level)) *MockLogger_SetLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logger.Level
		if args[0] != nil {
			arg0 = args[0].(logger.Level)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_SetLevel_Call) Return() *MockLogger_SetLevel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_SetLevel_Call) RunAndReturn(run func(level logger.Level)) *MockLogger_SetLevel_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, keyvals ...any) {
	if len(keyvals) > 0 {
		_mock.Called(msg, keyvals)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - keyvals ...any
func (_e *MockLogger_Expecter) Warn(msg interface{}, keyvals ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, keyvals...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, keyvals ...any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, keyvals ...any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}

// Warnf provides a mock function for the type MockLogger
func (_mock *MockLogger) Warnf(format string, args ...any) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Warnf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warnf'
type MockLogger_Warnf_Call struct {
	*mock.Call
}

// Warnf is a helper method to define mock.On call
//   - format string
//   - args ...any
func (_e *MockLogger_Expecter) Warnf(format interface{}, args ...interface{}) *MockLogger_Warnf_Call {
	return &MockLogger_Warnf_Call{Call: _e.mock.On("Warnf",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Warnf_Call) Run(run func(format string, args ...any)) *MockLogger_Warnf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Warnf_Call) Return() *MockLogger_Warnf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warnf_Call) RunAndReturn(run func(format string, args ...any)) *MockLogger_Warnf_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type MockLogger
func (_mock *MockLogger) With(keyvals ...any) logger.Logger {
	var tmpRet mock.Arguments
	if len(keyvals) > 0 {
		tmpRet = _mock.Called(keyvals)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(...any) logger.Logger); ok {
		r0 = returnFunc(keyvals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockLogger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockLogger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - keyvals ...any
func (_e *MockLogger_Expecter) With(keyvals ...interface{}) *MockLogger_With_Call {
	return &MockLogger_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, keyvals...)...)}
}

func (_c *MockLogger_With_Call) Run(run func(keyvals ...any)) *MockLogger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_With_Call) Return(logger1 logger.Logger) *MockLogger_With_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLogger_With_Call) RunAndReturn(run func(keyvals ...any) logger.Logger) *MockLogger_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithPrefix provides a mock function for the type MockLogger
func (_mock *MockLogger) WithPrefix(prefix string) logger.Logger {
	ret := _mock.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for WithPrefix")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func(string) logger.Logger); ok {
		r0 = returnFunc(prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockLogger_WithPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithPrefix'
type MockLogger_WithPrefix_Call struct {
	*mock.Call
}

// WithPrefix is a helper method to define mock.On call
//   - prefix string
func (_e *MockLogger_Expecter) WithPrefix(prefix interface{}) *MockLogger_WithPrefix_Call {
	return &MockLogger_WithPrefix_Call{Call: _e.mock.On("WithPrefix", prefix)}
}

func (_c *MockLogger_WithPrefix_Call) Run(run func(prefix string)) *MockLogger_WithPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogger_WithPrefix_Call) Return(logger1 logger.Logger) *MockLogger_WithPrefix_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLogger_WithPrefix_Call) RunAndReturn(run func(prefix string) logger.Logger) *MockLogger_WithPrefix_Call {
	_c.Call.Return(run)
	return _c
}
