// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package release

import (
	"context"
	"io"

	"github.com/phpboyscout/gtb/pkg/vcs/release"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// DownloadReleaseAsset provides a mock function for the type MockProvider
func (_mock *MockProvider) DownloadReleaseAsset(ctx context.Context, owner string, repo string, asset release.ReleaseAsset) (io.ReadCloser, string, error) {
	ret := _mock.Called(ctx, owner, repo, asset)

	if len(ret) == 0 {
		panic("no return value specified for DownloadReleaseAsset")
	}

	var r0 io.ReadCloser
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, release.ReleaseAsset) (io.ReadCloser, string, error)); ok {
		return returnFunc(ctx, owner, repo, asset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, release.ReleaseAsset) io.ReadCloser); ok {
		r0 = returnFunc(ctx, owner, repo, asset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, release.ReleaseAsset) string); ok {
		r1 = returnFunc(ctx, owner, repo, asset)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, release.ReleaseAsset) error); ok {
		r2 = returnFunc(ctx, owner, repo, asset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProvider_DownloadReleaseAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadReleaseAsset'
type MockProvider_DownloadReleaseAsset_Call struct {
	*mock.Call
}

// DownloadReleaseAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - asset release.ReleaseAsset
func (_e *MockProvider_Expecter) DownloadReleaseAsset(ctx interface{}, owner interface{}, repo interface{}, asset interface{}) *MockProvider_DownloadReleaseAsset_Call {
	return &MockProvider_DownloadReleaseAsset_Call{Call: _e.mock.On("DownloadReleaseAsset", ctx, owner, repo, asset)}
}

func (_c *MockProvider_DownloadReleaseAsset_Call) Run(run func(ctx context.Context, owner string, repo string, asset release.ReleaseAsset)) *MockProvider_DownloadReleaseAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 release.ReleaseAsset
		if args[3] != nil {
			arg3 = args[3].(release.ReleaseAsset)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProvider_DownloadReleaseAsset_Call) Return(readCloser io.ReadCloser, s string, err error) *MockProvider_DownloadReleaseAsset_Call {
	_c.Call.Return(readCloser, s, err)
	return _c
}

func (_c *MockProvider_DownloadReleaseAsset_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, asset release.ReleaseAsset) (io.ReadCloser, string, error)) *MockProvider_DownloadReleaseAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestRelease provides a mock function for the type MockProvider
func (_mock *MockProvider) GetLatestRelease(ctx context.Context, owner string, repo string) (release.Release, error) {
	ret := _mock.Called(ctx, owner, repo)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestRelease")
	}

	var r0 release.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (release.Release, error)); ok {
		return returnFunc(ctx, owner, repo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) release.Release); ok {
		r0 = returnFunc(ctx, owner, repo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(release.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetLatestRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestRelease'
type MockProvider_GetLatestRelease_Call struct {
	*mock.Call
}

// GetLatestRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
func (_e *MockProvider_Expecter) GetLatestRelease(ctx interface{}, owner interface{}, repo interface{}) *MockProvider_GetLatestRelease_Call {
	return &MockProvider_GetLatestRelease_Call{Call: _e.mock.On("GetLatestRelease", ctx, owner, repo)}
}

func (_c *MockProvider_GetLatestRelease_Call) Run(run func(ctx context.Context, owner string, repo string)) *MockProvider_GetLatestRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_GetLatestRelease_Call) Return(release1 release.Release, err error) *MockProvider_GetLatestRelease_Call {
	_c.Call.Return(release1, err)
	return _c
}

func (_c *MockProvider_GetLatestRelease_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string) (release.Release, error)) *MockProvider_GetLatestRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseByTag provides a mock function for the type MockProvider
func (_mock *MockProvider) GetReleaseByTag(ctx context.Context, owner string, repo string, tag string) (release.Release, error) {
	ret := _mock.Called(ctx, owner, repo, tag)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseByTag")
	}

	var r0 release.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (release.Release, error)); ok {
		return returnFunc(ctx, owner, repo, tag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) release.Release); ok {
		r0 = returnFunc(ctx, owner, repo, tag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(release.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, owner, repo, tag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetReleaseByTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseByTag'
type MockProvider_GetReleaseByTag_Call struct {
	*mock.Call
}

// GetReleaseByTag is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - tag string
func (_e *MockProvider_Expecter) GetReleaseByTag(ctx interface{}, owner interface{}, repo interface{}, tag interface{}) *MockProvider_GetReleaseByTag_Call {
	return &MockProvider_GetReleaseByTag_Call{Call: _e.mock.On("GetReleaseByTag", ctx, owner, repo, tag)}
}

func (_c *MockProvider_GetReleaseByTag_Call) Run(run func(ctx context.Context, owner string, repo string, tag string)) *MockProvider_GetReleaseByTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProvider_GetReleaseByTag_Call) Return(release1 release.Release, err error) *MockProvider_GetReleaseByTag_Call {
	_c.Call.Return(release1, err)
	return _c
}

func (_c *MockProvider_GetReleaseByTag_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, tag string) (release.Release, error)) *MockProvider_GetReleaseByTag_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleases provides a mock function for the type MockProvider
func (_mock *MockProvider) ListReleases(ctx context.Context, owner string, repo string, limit int) ([]release.Release, error) {
	ret := _mock.Called(ctx, owner, repo, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListReleases")
	}

	var r0 []release.Release
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]release.Release, error)); ok {
		return returnFunc(ctx, owner, repo, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []release.Release); ok {
		r0 = returnFunc(ctx, owner, repo, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]release.Release)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, owner, repo, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_ListReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleases'
type MockProvider_ListReleases_Call struct {
	*mock.Call
}

// ListReleases is a helper method to define mock.On call
//   - ctx context.Context
//   - owner string
//   - repo string
//   - limit int
func (_e *MockProvider_Expecter) ListReleases(ctx interface{}, owner interface{}, repo interface{}, limit interface{}) *MockProvider_ListReleases_Call {
	return &MockProvider_ListReleases_Call{Call: _e.mock.On("ListReleases", ctx, owner, repo, limit)}
}

func (_c *MockProvider_ListReleases_Call) Run(run func(ctx context.Context, owner string, repo string, limit int)) *MockProvider_ListReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProvider_ListReleases_Call) Return(releases []release.Release, err error) *MockProvider_ListReleases_Call {
	_c.Call.Return(releases, err)
	return _c
}

func (_c *MockProvider_ListReleases_Call) RunAndReturn(run func(ctx context.Context, owner string, repo string, limit int) ([]release.Release, error)) *MockProvider_ListReleases_Call {
	_c.Call.Return(run)
	return _c
}
