// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package release

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReleaseAsset creates a new instance of MockReleaseAsset. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReleaseAsset(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReleaseAsset {
	mock := &MockReleaseAsset{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReleaseAsset is an autogenerated mock type for the ReleaseAsset type
type MockReleaseAsset struct {
	mock.Mock
}

type MockReleaseAsset_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReleaseAsset) EXPECT() *MockReleaseAsset_Expecter {
	return &MockReleaseAsset_Expecter{mock: &_m.Mock}
}

// GetBrowserDownloadURL provides a mock function for the type MockReleaseAsset
func (_mock *MockReleaseAsset) GetBrowserDownloadURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBrowserDownloadURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReleaseAsset_GetBrowserDownloadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBrowserDownloadURL'
type MockReleaseAsset_GetBrowserDownloadURL_Call struct {
	*mock.Call
}

// GetBrowserDownloadURL is a helper method to define mock.On call
func (_e *MockReleaseAsset_Expecter) GetBrowserDownloadURL() *MockReleaseAsset_GetBrowserDownloadURL_Call {
	return &MockReleaseAsset_GetBrowserDownloadURL_Call{Call: _e.mock.On("GetBrowserDownloadURL")}
}

func (_c *MockReleaseAsset_GetBrowserDownloadURL_Call) Run(run func()) *MockReleaseAsset_GetBrowserDownloadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReleaseAsset_GetBrowserDownloadURL_Call) Return(s string) *MockReleaseAsset_GetBrowserDownloadURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReleaseAsset_GetBrowserDownloadURL_Call) RunAndReturn(run func() string) *MockReleaseAsset_GetBrowserDownloadURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockReleaseAsset
func (_mock *MockReleaseAsset) GetID() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockReleaseAsset_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockReleaseAsset_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockReleaseAsset_Expecter) GetID() *MockReleaseAsset_GetID_Call {
	return &MockReleaseAsset_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockReleaseAsset_GetID_Call) Run(run func()) *MockReleaseAsset_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReleaseAsset_GetID_Call) Return(n int64) *MockReleaseAsset_GetID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReleaseAsset_GetID_Call) RunAndReturn(run func() int64) *MockReleaseAsset_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockReleaseAsset
func (_mock *MockReleaseAsset) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReleaseAsset_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockReleaseAsset_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockReleaseAsset_Expecter) GetName() *MockReleaseAsset_GetName_Call {
	return &MockReleaseAsset_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockReleaseAsset_GetName_Call) Run(run func()) *MockReleaseAsset_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReleaseAsset_GetName_Call) Return(s string) *MockReleaseAsset_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReleaseAsset_GetName_Call) RunAndReturn(run func() string) *MockReleaseAsset_GetName_Call {
	_c.Call.Return(run)
	return _c
}
