// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controls

import (
	"context"
	"log/slog"
	"os"
	"sync"
	"time"

	"github.com/phpboyscout/gtb/pkg/controls"
	mock "github.com/stretchr/testify/mock"
)

// NewMockControllable creates a new instance of MockControllable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockControllable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockControllable {
	mock := &MockControllable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockControllable is an autogenerated mock type for the Controllable type
type MockControllable struct {
	mock.Mock
}

type MockControllable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockControllable) EXPECT() *MockControllable_Expecter {
	return &MockControllable_Expecter{mock: &_m.Mock}
}

// Errors provides a mock function for the type MockControllable
func (_mock *MockControllable) Errors() chan error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Errors")
	}

	var r0 chan error
	if returnFunc, ok := ret.Get(0).(func() chan error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan error)
		}
	}
	return r0
}

// MockControllable_Errors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errors'
type MockControllable_Errors_Call struct {
	*mock.Call
}

// Errors is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Errors() *MockControllable_Errors_Call {
	return &MockControllable_Errors_Call{Call: _e.mock.On("Errors")}
}

func (_c *MockControllable_Errors_Call) Run(run func()) *MockControllable_Errors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Errors_Call) Return(errCh chan error) *MockControllable_Errors_Call {
	_c.Call.Return(errCh)
	return _c
}

func (_c *MockControllable_Errors_Call) RunAndReturn(run func() chan error) *MockControllable_Errors_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type MockControllable
func (_mock *MockControllable) GetContext() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockControllable_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockControllable_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockControllable_Expecter) GetContext() *MockControllable_GetContext_Call {
	return &MockControllable_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockControllable_GetContext_Call) Run(run func()) *MockControllable_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_GetContext_Call) Return(context1 context.Context) *MockControllable_GetContext_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockControllable_GetContext_Call) RunAndReturn(run func() context.Context) *MockControllable_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockControllable
func (_mock *MockControllable) GetLogger() *slog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 *slog.Logger
	if returnFunc, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}
	return r0
}

// MockControllable_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockControllable_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockControllable_Expecter) GetLogger() *MockControllable_GetLogger_Call {
	return &MockControllable_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockControllable_GetLogger_Call) Run(run func()) *MockControllable_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_GetLogger_Call) Return(logger *slog.Logger) *MockControllable_GetLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockControllable_GetLogger_Call) RunAndReturn(run func() *slog.Logger) *MockControllable_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockControllable
func (_mock *MockControllable) GetState() controls.State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 controls.State
	if returnFunc, ok := ret.Get(0).(func() controls.State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(controls.State)
	}
	return r0
}

// MockControllable_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockControllable_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *MockControllable_Expecter) GetState() *MockControllable_GetState_Call {
	return &MockControllable_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *MockControllable_GetState_Call) Run(run func()) *MockControllable_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_GetState_Call) Return(state controls.State) *MockControllable_GetState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *MockControllable_GetState_Call) RunAndReturn(run func() controls.State) *MockControllable_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type MockControllable
func (_mock *MockControllable) Health() chan controls.HealthMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 chan controls.HealthMessage
	if returnFunc, ok := ret.Get(0).(func() chan controls.HealthMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan controls.HealthMessage)
		}
	}
	return r0
}

// MockControllable_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockControllable_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Health() *MockControllable_Health_Call {
	return &MockControllable_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *MockControllable_Health_Call) Run(run func()) *MockControllable_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Health_Call) Return(healthMessageCh chan controls.HealthMessage) *MockControllable_Health_Call {
	_c.Call.Return(healthMessageCh)
	return _c
}

func (_c *MockControllable_Health_Call) RunAndReturn(run func() chan controls.HealthMessage) *MockControllable_Health_Call {
	_c.Call.Return(run)
	return _c
}

// IsRunning provides a mock function for the type MockControllable
func (_mock *MockControllable) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockControllable_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockControllable_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockControllable_Expecter) IsRunning() *MockControllable_IsRunning_Call {
	return &MockControllable_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockControllable_IsRunning_Call) Run(run func()) *MockControllable_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_IsRunning_Call) Return(b bool) *MockControllable_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockControllable_IsRunning_Call) RunAndReturn(run func() bool) *MockControllable_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopped provides a mock function for the type MockControllable
func (_mock *MockControllable) IsStopped() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopped")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockControllable_IsStopped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopped'
type MockControllable_IsStopped_Call struct {
	*mock.Call
}

// IsStopped is a helper method to define mock.On call
func (_e *MockControllable_Expecter) IsStopped() *MockControllable_IsStopped_Call {
	return &MockControllable_IsStopped_Call{Call: _e.mock.On("IsStopped")}
}

func (_c *MockControllable_IsStopped_Call) Run(run func()) *MockControllable_IsStopped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_IsStopped_Call) Return(b bool) *MockControllable_IsStopped_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockControllable_IsStopped_Call) RunAndReturn(run func() bool) *MockControllable_IsStopped_Call {
	_c.Call.Return(run)
	return _c
}

// IsStopping provides a mock function for the type MockControllable
func (_mock *MockControllable) IsStopping() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsStopping")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockControllable_IsStopping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsStopping'
type MockControllable_IsStopping_Call struct {
	*mock.Call
}

// IsStopping is a helper method to define mock.On call
func (_e *MockControllable_Expecter) IsStopping() *MockControllable_IsStopping_Call {
	return &MockControllable_IsStopping_Call{Call: _e.mock.On("IsStopping")}
}

func (_c *MockControllable_IsStopping_Call) Run(run func()) *MockControllable_IsStopping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_IsStopping_Call) Return(b bool) *MockControllable_IsStopping_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockControllable_IsStopping_Call) RunAndReturn(run func() bool) *MockControllable_IsStopping_Call {
	_c.Call.Return(run)
	return _c
}

// Messages provides a mock function for the type MockControllable
func (_mock *MockControllable) Messages() chan controls.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 chan controls.Message
	if returnFunc, ok := ret.Get(0).(func() chan controls.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan controls.Message)
		}
	}
	return r0
}

// MockControllable_Messages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Messages'
type MockControllable_Messages_Call struct {
	*mock.Call
}

// Messages is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Messages() *MockControllable_Messages_Call {
	return &MockControllable_Messages_Call{Call: _e.mock.On("Messages")}
}

func (_c *MockControllable_Messages_Call) Run(run func()) *MockControllable_Messages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Messages_Call) Return(messageCh chan controls.Message) *MockControllable_Messages_Call {
	_c.Call.Return(messageCh)
	return _c
}

func (_c *MockControllable_Messages_Call) RunAndReturn(run func() chan controls.Message) *MockControllable_Messages_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockControllable
func (_mock *MockControllable) Register(id string, opts ...controls.ServiceOption) {
	if len(opts) > 0 {
		_mock.Called(id, opts)
	} else {
		_mock.Called(id)
	}

	return
}

// MockControllable_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockControllable_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - id string
//   - opts ...controls.ServiceOption
func (_e *MockControllable_Expecter) Register(id interface{}, opts ...interface{}) *MockControllable_Register_Call {
	return &MockControllable_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{id}, opts...)...)}
}

func (_c *MockControllable_Register_Call) Run(run func(id string, opts ...controls.ServiceOption)) *MockControllable_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []controls.ServiceOption
		var variadicArgs []controls.ServiceOption
		if len(args) > 1 {
			variadicArgs = args[1].([]controls.ServiceOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockControllable_Register_Call) Return() *MockControllable_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_Register_Call) RunAndReturn(run func(id string, opts ...controls.ServiceOption)) *MockControllable_Register_Call {
	_c.Run(run)
	return _c
}

// SetErrorsChannel provides a mock function for the type MockControllable
func (_mock *MockControllable) SetErrorsChannel(errs chan error) {
	_mock.Called(errs)
	return
}

// MockControllable_SetErrorsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetErrorsChannel'
type MockControllable_SetErrorsChannel_Call struct {
	*mock.Call
}

// SetErrorsChannel is a helper method to define mock.On call
//   - errs chan error
func (_e *MockControllable_Expecter) SetErrorsChannel(errs interface{}) *MockControllable_SetErrorsChannel_Call {
	return &MockControllable_SetErrorsChannel_Call{Call: _e.mock.On("SetErrorsChannel", errs)}
}

func (_c *MockControllable_SetErrorsChannel_Call) Run(run func(errs chan error)) *MockControllable_SetErrorsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan error
		if args[0] != nil {
			arg0 = args[0].(chan error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetErrorsChannel_Call) Return() *MockControllable_SetErrorsChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetErrorsChannel_Call) RunAndReturn(run func(errs chan error)) *MockControllable_SetErrorsChannel_Call {
	_c.Run(run)
	return _c
}

// SetHealthChannel provides a mock function for the type MockControllable
func (_mock *MockControllable) SetHealthChannel(health chan controls.HealthMessage) {
	_mock.Called(health)
	return
}

// MockControllable_SetHealthChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHealthChannel'
type MockControllable_SetHealthChannel_Call struct {
	*mock.Call
}

// SetHealthChannel is a helper method to define mock.On call
//   - health chan controls.HealthMessage
func (_e *MockControllable_Expecter) SetHealthChannel(health interface{}) *MockControllable_SetHealthChannel_Call {
	return &MockControllable_SetHealthChannel_Call{Call: _e.mock.On("SetHealthChannel", health)}
}

func (_c *MockControllable_SetHealthChannel_Call) Run(run func(health chan controls.HealthMessage)) *MockControllable_SetHealthChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan controls.HealthMessage
		if args[0] != nil {
			arg0 = args[0].(chan controls.HealthMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetHealthChannel_Call) Return() *MockControllable_SetHealthChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetHealthChannel_Call) RunAndReturn(run func(health chan controls.HealthMessage)) *MockControllable_SetHealthChannel_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockControllable
func (_mock *MockControllable) SetLogger(logger *slog.Logger) {
	_mock.Called(logger)
	return
}

// MockControllable_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockControllable_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *slog.Logger
func (_e *MockControllable_Expecter) SetLogger(logger interface{}) *MockControllable_SetLogger_Call {
	return &MockControllable_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockControllable_SetLogger_Call) Run(run func(logger *slog.Logger)) *MockControllable_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *slog.Logger
		if args[0] != nil {
			arg0 = args[0].(*slog.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetLogger_Call) Return() *MockControllable_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetLogger_Call) RunAndReturn(run func(logger *slog.Logger)) *MockControllable_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetMessageChannel provides a mock function for the type MockControllable
func (_mock *MockControllable) SetMessageChannel(control chan controls.Message) {
	_mock.Called(control)
	return
}

// MockControllable_SetMessageChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetMessageChannel'
type MockControllable_SetMessageChannel_Call struct {
	*mock.Call
}

// SetMessageChannel is a helper method to define mock.On call
//   - control chan controls.Message
func (_e *MockControllable_Expecter) SetMessageChannel(control interface{}) *MockControllable_SetMessageChannel_Call {
	return &MockControllable_SetMessageChannel_Call{Call: _e.mock.On("SetMessageChannel", control)}
}

func (_c *MockControllable_SetMessageChannel_Call) Run(run func(control chan controls.Message)) *MockControllable_SetMessageChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan controls.Message
		if args[0] != nil {
			arg0 = args[0].(chan controls.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetMessageChannel_Call) Return() *MockControllable_SetMessageChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetMessageChannel_Call) RunAndReturn(run func(control chan controls.Message)) *MockControllable_SetMessageChannel_Call {
	_c.Run(run)
	return _c
}

// SetShutdownTimeout provides a mock function for the type MockControllable
func (_mock *MockControllable) SetShutdownTimeout(d time.Duration) {
	_mock.Called(d)
	return
}

// MockControllable_SetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShutdownTimeout'
type MockControllable_SetShutdownTimeout_Call struct {
	*mock.Call
}

// SetShutdownTimeout is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockControllable_Expecter) SetShutdownTimeout(d interface{}) *MockControllable_SetShutdownTimeout_Call {
	return &MockControllable_SetShutdownTimeout_Call{Call: _e.mock.On("SetShutdownTimeout", d)}
}

func (_c *MockControllable_SetShutdownTimeout_Call) Run(run func(d time.Duration)) *MockControllable_SetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetShutdownTimeout_Call) Return() *MockControllable_SetShutdownTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetShutdownTimeout_Call) RunAndReturn(run func(d time.Duration)) *MockControllable_SetShutdownTimeout_Call {
	_c.Run(run)
	return _c
}

// SetSignalsChannel provides a mock function for the type MockControllable
func (_mock *MockControllable) SetSignalsChannel(sigs chan os.Signal) {
	_mock.Called(sigs)
	return
}

// MockControllable_SetSignalsChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSignalsChannel'
type MockControllable_SetSignalsChannel_Call struct {
	*mock.Call
}

// SetSignalsChannel is a helper method to define mock.On call
//   - sigs chan os.Signal
func (_e *MockControllable_Expecter) SetSignalsChannel(sigs interface{}) *MockControllable_SetSignalsChannel_Call {
	return &MockControllable_SetSignalsChannel_Call{Call: _e.mock.On("SetSignalsChannel", sigs)}
}

func (_c *MockControllable_SetSignalsChannel_Call) Run(run func(sigs chan os.Signal)) *MockControllable_SetSignalsChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan os.Signal
		if args[0] != nil {
			arg0 = args[0].(chan os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetSignalsChannel_Call) Return() *MockControllable_SetSignalsChannel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetSignalsChannel_Call) RunAndReturn(run func(sigs chan os.Signal)) *MockControllable_SetSignalsChannel_Call {
	_c.Run(run)
	return _c
}

// SetState provides a mock function for the type MockControllable
func (_mock *MockControllable) SetState(state controls.State) {
	_mock.Called(state)
	return
}

// MockControllable_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockControllable_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - state controls.State
func (_e *MockControllable_Expecter) SetState(state interface{}) *MockControllable_SetState_Call {
	return &MockControllable_SetState_Call{Call: _e.mock.On("SetState", state)}
}

func (_c *MockControllable_SetState_Call) Run(run func(state controls.State)) *MockControllable_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 controls.State
		if args[0] != nil {
			arg0 = args[0].(controls.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetState_Call) Return() *MockControllable_SetState_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetState_Call) RunAndReturn(run func(state controls.State)) *MockControllable_SetState_Call {
	_c.Run(run)
	return _c
}

// SetWaitGroup provides a mock function for the type MockControllable
func (_mock *MockControllable) SetWaitGroup(wg *sync.WaitGroup) {
	_mock.Called(wg)
	return
}

// MockControllable_SetWaitGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaitGroup'
type MockControllable_SetWaitGroup_Call struct {
	*mock.Call
}

// SetWaitGroup is a helper method to define mock.On call
//   - wg *sync.WaitGroup
func (_e *MockControllable_Expecter) SetWaitGroup(wg interface{}) *MockControllable_SetWaitGroup_Call {
	return &MockControllable_SetWaitGroup_Call{Call: _e.mock.On("SetWaitGroup", wg)}
}

func (_c *MockControllable_SetWaitGroup_Call) Run(run func(wg *sync.WaitGroup)) *MockControllable_SetWaitGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sync.WaitGroup
		if args[0] != nil {
			arg0 = args[0].(*sync.WaitGroup)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockControllable_SetWaitGroup_Call) Return() *MockControllable_SetWaitGroup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_SetWaitGroup_Call) RunAndReturn(run func(wg *sync.WaitGroup)) *MockControllable_SetWaitGroup_Call {
	_c.Run(run)
	return _c
}

// Signals provides a mock function for the type MockControllable
func (_mock *MockControllable) Signals() chan os.Signal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Signals")
	}

	var r0 chan os.Signal
	if returnFunc, ok := ret.Get(0).(func() chan os.Signal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan os.Signal)
		}
	}
	return r0
}

// MockControllable_Signals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signals'
type MockControllable_Signals_Call struct {
	*mock.Call
}

// Signals is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Signals() *MockControllable_Signals_Call {
	return &MockControllable_Signals_Call{Call: _e.mock.On("Signals")}
}

func (_c *MockControllable_Signals_Call) Run(run func()) *MockControllable_Signals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Signals_Call) Return(signalCh chan os.Signal) *MockControllable_Signals_Call {
	_c.Call.Return(signalCh)
	return _c
}

func (_c *MockControllable_Signals_Call) RunAndReturn(run func() chan os.Signal) *MockControllable_Signals_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockControllable
func (_mock *MockControllable) Start() {
	_mock.Called()
	return
}

// MockControllable_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockControllable_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Start() *MockControllable_Start_Call {
	return &MockControllable_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockControllable_Start_Call) Run(run func()) *MockControllable_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Start_Call) Return() *MockControllable_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_Start_Call) RunAndReturn(run func()) *MockControllable_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockControllable
func (_mock *MockControllable) Stop() {
	_mock.Called()
	return
}

// MockControllable_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockControllable_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockControllable_Expecter) Stop() *MockControllable_Stop_Call {
	return &MockControllable_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockControllable_Stop_Call) Run(run func()) *MockControllable_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockControllable_Stop_Call) Return() *MockControllable_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockControllable_Stop_Call) RunAndReturn(run func()) *MockControllable_Stop_Call {
	_c.Run(run)
	return _c
}
