package generator

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/cockroachdb/errors"

	"github.com/phpboyscout/gtb/pkg/chat"
	"github.com/phpboyscout/gtb/pkg/props"
	"github.com/phpboyscout/gtb/pkg/version"
)

const (
	DefaultFileMode = 0o644
	DefaultDirMode  = 0o755
)

type Config struct {
	Agentless        bool
	AIModel          string
	AIProvider       string
	Aliases          []string
	Args             string
	Flags            []string
	Force            bool
	Hidden           bool
	Overwrite        string // allow, deny, or ask (default ask)
	Long             string
	Name             string
	Parent           string
	Path             string
	PersistentPreRun bool
	PreRun           bool
	Prompt           string
	Protected        *bool
	ScriptPath       string
	Short            string
	UpdateDocs       bool
	WithAssets       bool
	WithInitializer  bool
}

type CommandFlag struct {
	Default       string
	DefaultIsCode bool
	Description   string
	Hidden        bool
	Name          string
	Persistent    bool
	Required      bool
	Shorthand     string
	Type          string
}

type Generator struct {
	props      *props.Props
	config     *Config
	chatClient chat.ChatClient
	runCommand func(ctx context.Context, dir, name string, args ...string) ([]byte, error)
}

func New(p *props.Props, cfg *Config) *Generator {
	return &Generator{
		props:  p,
		config: cfg,
	}
}

func (g *Generator) SetProtection(ctx context.Context, commandName string, protected bool) error {
	pathParts := strings.Split(commandName, "/")
	name := pathParts[len(pathParts)-1]

	// Create a minimal config for finding/updating the command
	g.config.Name = name
	g.config.Protected = &protected

	if len(pathParts) > 1 {
		g.config.Parent = pathParts[len(pathParts)-2]
	}

	// We need to use updateManifest logic, but tailored for just setting protection
	// Since updateManifest relies on g.config, we can reuse it but we need to be careful not to overwrite other fields with defaults.
	// However, updateManifest merges with existing unless it's a new command.
	// A better approach here might be to treat this as a specific manifest update.

	// Re-reading manifest.go, updateManifest reads existing manifest.
	// It uses updateCommandRecursive to find and update.
	// If we set g.config.Name and g.config.Protected, and call updateManifest with empty flags?
	// The problem is updateManifest overwrites description etc from g.config.

	// Let's implement a specific update for protection to avoid side effects.

	// Implementation logic:
	// 1. Read manifest
	// 2. Find command
	// 3. Set Protected
	// 4. Write manifest

	// Wait, we can modify the Generator receiver to support this cleaner.
	// But sticking to the plan, let me implement the logic here cleanly.

	// Refactoring to use generic manifest update helpers would be ideal but for now let's implement the specific logic.

	return g.updateProtectionInManifest(name, pathParts, protected)
}

func (g *Generator) updateProtectionInManifest(name string, pathParts []string, protected bool) error {
	// We need to access the manifest file.
	// Since this is inside generator package, we can duplicate the read/write logic or expose helpers.
	// Given the constraints and file structure, I will duplicate the read/write logic for safety to avoid changing manifest.go public API too much if not needed.
	// Actually, I can add this method to manifest.go instead?
	// No, the plan says generator.go. But updateManifest is in manifest.go.
	// I will implementation SetProtection here and delegate the actual update logic to a new method in manifest.go for consistency.
	return g.setCommandProtection(name, pathParts, protected)
}

func PascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}

	return strings.Join(parts, "")
}

func (g *Generator) verifyProject() error {
	manifestPath := filepath.Join(g.config.Path, ".gtb", "manifest.yaml")

	if _, err := g.props.FS.Stat(manifestPath); os.IsNotExist(err) {
		return errors.Newf("Warning: "+ErrNotGoToolBaseProject.Error()+". Please run 'generate skeleton' first", g.config.Path)
	}

	m, _ := g.loadManifest()
	if m == nil {
		return nil
	}

	return g.checkManifestVersion(m)
}

func (g *Generator) checkManifestVersion(m *Manifest) error {
	cliVer := ""
	if g.props.Version != nil {
		cliVer = g.props.Version.GetVersion()
	}

	// Dev builds bypass checks
	if g.props.Version == nil || g.props.Version.IsDevelopment() || cliVer == "" {
		return nil
	}

	manifestVer := m.Version.GoToolBase

	// If manifest was generated by a dev build, treat as incompatible
	if manifestVer == "dev" || manifestVer == "" {
		return errors.Newf("current gtb version (%s) is lower than the version specified in the manifest (%s). Please update gtb", cliVer, manifestVer)
	}

	if version.CompareVersions(cliVer, manifestVer) < 0 {
		return errors.Newf("current gtb version (%s) is lower than the version specified in the manifest (%s). Please update gtb: go install github.com/phpboyscout/gtb@latest", cliVer, manifestVer)
	}

	if version.CompareVersions(cliVer, manifestVer) > 0 {
		g.checkBreakingChanges(manifestVer, cliVer)
	}

	return nil
}

func (g *Generator) checkBreakingChanges(manifestVer, cliVer string) {
	for ver, msg := range BreakingChanges {
		// If version is newer than manifest AND older than or equal to current CLI
		// using > and <= comparisons
		if version.CompareVersions(ver, manifestVer) > 0 && version.CompareVersions(ver, cliVer) <= 0 {
			g.props.Logger.Warnf("Project update required for %s: %s", ver, msg)
		}
	}
}

func (g *Generator) getImportPath() (string, error) {
	moduleName, err := g.getModuleName()
	if err != nil {
		return "", err
	}

	cmdSubPath, err := g.getCommandPath()
	if err != nil {
		return "", err
	}

	relCmdPath, err := filepath.Rel(g.config.Path, cmdSubPath)
	if err != nil {
		return "", err
	}

	return fmt.Sprintf("%s/%s", moduleName, relCmdPath), nil
}
