// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package release

import (
	"github.com/phpboyscout/gtb/pkg/vcs/release"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRelease creates a new instance of MockRelease. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelease(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelease {
	mock := &MockRelease{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRelease is an autogenerated mock type for the Release type
type MockRelease struct {
	mock.Mock
}

type MockRelease_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelease) EXPECT() *MockRelease_Expecter {
	return &MockRelease_Expecter{mock: &_m.Mock}
}

// GetAssets provides a mock function for the type MockRelease
func (_mock *MockRelease) GetAssets() []release.ReleaseAsset {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAssets")
	}

	var r0 []release.ReleaseAsset
	if returnFunc, ok := ret.Get(0).(func() []release.ReleaseAsset); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]release.ReleaseAsset)
		}
	}
	return r0
}

// MockRelease_GetAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssets'
type MockRelease_GetAssets_Call struct {
	*mock.Call
}

// GetAssets is a helper method to define mock.On call
func (_e *MockRelease_Expecter) GetAssets() *MockRelease_GetAssets_Call {
	return &MockRelease_GetAssets_Call{Call: _e.mock.On("GetAssets")}
}

func (_c *MockRelease_GetAssets_Call) Run(run func()) *MockRelease_GetAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelease_GetAssets_Call) Return(releaseAssets []release.ReleaseAsset) *MockRelease_GetAssets_Call {
	_c.Call.Return(releaseAssets)
	return _c
}

func (_c *MockRelease_GetAssets_Call) RunAndReturn(run func() []release.ReleaseAsset) *MockRelease_GetAssets_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function for the type MockRelease
func (_mock *MockRelease) GetBody() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRelease_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type MockRelease_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *MockRelease_Expecter) GetBody() *MockRelease_GetBody_Call {
	return &MockRelease_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *MockRelease_GetBody_Call) Run(run func()) *MockRelease_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelease_GetBody_Call) Return(s string) *MockRelease_GetBody_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRelease_GetBody_Call) RunAndReturn(run func() string) *MockRelease_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetDraft provides a mock function for the type MockRelease
func (_mock *MockRelease) GetDraft() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDraft")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockRelease_GetDraft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDraft'
type MockRelease_GetDraft_Call struct {
	*mock.Call
}

// GetDraft is a helper method to define mock.On call
func (_e *MockRelease_Expecter) GetDraft() *MockRelease_GetDraft_Call {
	return &MockRelease_GetDraft_Call{Call: _e.mock.On("GetDraft")}
}

func (_c *MockRelease_GetDraft_Call) Run(run func()) *MockRelease_GetDraft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelease_GetDraft_Call) Return(b bool) *MockRelease_GetDraft_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockRelease_GetDraft_Call) RunAndReturn(run func() bool) *MockRelease_GetDraft_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function for the type MockRelease
func (_mock *MockRelease) GetName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRelease_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockRelease_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockRelease_Expecter) GetName() *MockRelease_GetName_Call {
	return &MockRelease_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockRelease_GetName_Call) Run(run func()) *MockRelease_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelease_GetName_Call) Return(s string) *MockRelease_GetName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRelease_GetName_Call) RunAndReturn(run func() string) *MockRelease_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagName provides a mock function for the type MockRelease
func (_mock *MockRelease) GetTagName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTagName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRelease_GetTagName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagName'
type MockRelease_GetTagName_Call struct {
	*mock.Call
}

// GetTagName is a helper method to define mock.On call
func (_e *MockRelease_Expecter) GetTagName() *MockRelease_GetTagName_Call {
	return &MockRelease_GetTagName_Call{Call: _e.mock.On("GetTagName")}
}

func (_c *MockRelease_GetTagName_Call) Run(run func()) *MockRelease_GetTagName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRelease_GetTagName_Call) Return(s string) *MockRelease_GetTagName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRelease_GetTagName_Call) RunAndReturn(run func() string) *MockRelease_GetTagName_Call {
	_c.Call.Return(run)
	return _c
}
