// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package chat

import (
	"context"

	"github.com/phpboyscout/gtb/pkg/chat"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatClient creates a new instance of MockChatClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatClient {
	mock := &MockChatClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatClient is an autogenerated mock type for the ChatClient type
type MockChatClient struct {
	mock.Mock
}

type MockChatClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatClient) EXPECT() *MockChatClient_Expecter {
	return &MockChatClient_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockChatClient
func (_mock *MockChatClient) Add(prompt string) error {
	ret := _mock.Called(prompt)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(prompt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatClient_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockChatClient_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - prompt string
func (_e *MockChatClient_Expecter) Add(prompt interface{}) *MockChatClient_Add_Call {
	return &MockChatClient_Add_Call{Call: _e.mock.On("Add", prompt)}
}

func (_c *MockChatClient_Add_Call) Run(run func(prompt string)) *MockChatClient_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatClient_Add_Call) Return(err error) *MockChatClient_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatClient_Add_Call) RunAndReturn(run func(prompt string) error) *MockChatClient_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Ask provides a mock function for the type MockChatClient
func (_mock *MockChatClient) Ask(question string, target any) error {
	ret := _mock.Called(question, target)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = returnFunc(question, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatClient_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type MockChatClient_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - question string
//   - target any
func (_e *MockChatClient_Expecter) Ask(question interface{}, target interface{}) *MockChatClient_Ask_Call {
	return &MockChatClient_Ask_Call{Call: _e.mock.On("Ask", question, target)}
}

func (_c *MockChatClient_Ask_Call) Run(run func(question string, target any)) *MockChatClient_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatClient_Ask_Call) Return(err error) *MockChatClient_Ask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatClient_Ask_Call) RunAndReturn(run func(question string, target any) error) *MockChatClient_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function for the type MockChatClient
func (_mock *MockChatClient) Chat(ctx context.Context, prompt string) (string, error) {
	ret := _mock.Called(ctx, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, prompt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, prompt)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prompt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatClient_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockChatClient_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
func (_e *MockChatClient_Expecter) Chat(ctx interface{}, prompt interface{}) *MockChatClient_Chat_Call {
	return &MockChatClient_Chat_Call{Call: _e.mock.On("Chat", ctx, prompt)}
}

func (_c *MockChatClient_Chat_Call) Run(run func(ctx context.Context, prompt string)) *MockChatClient_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatClient_Chat_Call) Return(s string, err error) *MockChatClient_Chat_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChatClient_Chat_Call) RunAndReturn(run func(ctx context.Context, prompt string) (string, error)) *MockChatClient_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// SetTools provides a mock function for the type MockChatClient
func (_mock *MockChatClient) SetTools(tools []chat.Tool) error {
	ret := _mock.Called(tools)

	if len(ret) == 0 {
		panic("no return value specified for SetTools")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]chat.Tool) error); ok {
		r0 = returnFunc(tools)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatClient_SetTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTools'
type MockChatClient_SetTools_Call struct {
	*mock.Call
}

// SetTools is a helper method to define mock.On call
//   - tools []chat.Tool
func (_e *MockChatClient_Expecter) SetTools(tools interface{}) *MockChatClient_SetTools_Call {
	return &MockChatClient_SetTools_Call{Call: _e.mock.On("SetTools", tools)}
}

func (_c *MockChatClient_SetTools_Call) Run(run func(tools []chat.Tool)) *MockChatClient_SetTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []chat.Tool
		if args[0] != nil {
			arg0 = args[0].([]chat.Tool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatClient_SetTools_Call) Return(err error) *MockChatClient_SetTools_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatClient_SetTools_Call) RunAndReturn(run func(tools []chat.Tool) error) *MockChatClient_SetTools_Call {
	_c.Call.Return(run)
	return _c
}
