// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/props"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAssetProvider creates a new instance of MockAssetProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssetProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssetProvider {
	mock := &MockAssetProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAssetProvider is an autogenerated mock type for the AssetProvider type
type MockAssetProvider struct {
	mock.Mock
}

type MockAssetProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAssetProvider) EXPECT() *MockAssetProvider_Expecter {
	return &MockAssetProvider_Expecter{mock: &_m.Mock}
}

// GetAssets provides a mock function for the type MockAssetProvider
func (_mock *MockAssetProvider) GetAssets() props.Assets {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAssets")
	}

	var r0 props.Assets
	if returnFunc, ok := ret.Get(0).(func() props.Assets); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(props.Assets)
		}
	}
	return r0
}

// MockAssetProvider_GetAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAssets'
type MockAssetProvider_GetAssets_Call struct {
	*mock.Call
}

// GetAssets is a helper method to define mock.On call
func (_e *MockAssetProvider_Expecter) GetAssets() *MockAssetProvider_GetAssets_Call {
	return &MockAssetProvider_GetAssets_Call{Call: _e.mock.On("GetAssets")}
}

func (_c *MockAssetProvider_GetAssets_Call) Run(run func()) *MockAssetProvider_GetAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAssetProvider_GetAssets_Call) Return(assets props.Assets) *MockAssetProvider_GetAssets_Call {
	_c.Call.Return(assets)
	return _c
}

func (_c *MockAssetProvider_GetAssets_Call) RunAndReturn(run func() props.Assets) *MockAssetProvider_GetAssets_Call {
	_c.Call.Return(run)
	return _c
}
