// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigProvider creates a new instance of MockConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigProvider {
	mock := &MockConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigProvider is an autogenerated mock type for the ConfigProvider type
type MockConfigProvider struct {
	mock.Mock
}

type MockConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigProvider) EXPECT() *MockConfigProvider_Expecter {
	return &MockConfigProvider_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type MockConfigProvider
func (_mock *MockConfigProvider) GetConfig() config.Containable {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.Containable
	if returnFunc, ok := ret.Get(0).(func() config.Containable); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Containable)
		}
	}
	return r0
}

// MockConfigProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockConfigProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockConfigProvider_Expecter) GetConfig() *MockConfigProvider_GetConfig_Call {
	return &MockConfigProvider_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockConfigProvider_GetConfig_Call) Run(run func()) *MockConfigProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigProvider_GetConfig_Call) Return(containable config.Containable) *MockConfigProvider_GetConfig_Call {
	_c.Call.Return(containable)
	return _c
}

func (_c *MockConfigProvider_GetConfig_Call) RunAndReturn(run func() config.Containable) *MockConfigProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}
