// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/config"
	"github.com/phpboyscout/go-tool-base/pkg/logger"
	"github.com/spf13/afero"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCoreProvider creates a new instance of MockCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoreProvider {
	mock := &MockCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCoreProvider is an autogenerated mock type for the CoreProvider type
type MockCoreProvider struct {
	mock.Mock
}

type MockCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoreProvider) EXPECT() *MockCoreProvider_Expecter {
	return &MockCoreProvider_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type MockCoreProvider
func (_mock *MockCoreProvider) GetConfig() config.Containable {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.Containable
	if returnFunc, ok := ret.Get(0).(func() config.Containable); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Containable)
		}
	}
	return r0
}

// MockCoreProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockCoreProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockCoreProvider_Expecter) GetConfig() *MockCoreProvider_GetConfig_Call {
	return &MockCoreProvider_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockCoreProvider_GetConfig_Call) Run(run func()) *MockCoreProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreProvider_GetConfig_Call) Return(containable config.Containable) *MockCoreProvider_GetConfig_Call {
	_c.Call.Return(containable)
	return _c
}

func (_c *MockCoreProvider_GetConfig_Call) RunAndReturn(run func() config.Containable) *MockCoreProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetFS provides a mock function for the type MockCoreProvider
func (_mock *MockCoreProvider) GetFS() afero.Fs {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFS")
	}

	var r0 afero.Fs
	if returnFunc, ok := ret.Get(0).(func() afero.Fs); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}
	return r0
}

// MockCoreProvider_GetFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFS'
type MockCoreProvider_GetFS_Call struct {
	*mock.Call
}

// GetFS is a helper method to define mock.On call
func (_e *MockCoreProvider_Expecter) GetFS() *MockCoreProvider_GetFS_Call {
	return &MockCoreProvider_GetFS_Call{Call: _e.mock.On("GetFS")}
}

func (_c *MockCoreProvider_GetFS_Call) Run(run func()) *MockCoreProvider_GetFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreProvider_GetFS_Call) Return(fs afero.Fs) *MockCoreProvider_GetFS_Call {
	_c.Call.Return(fs)
	return _c
}

func (_c *MockCoreProvider_GetFS_Call) RunAndReturn(run func() afero.Fs) *MockCoreProvider_GetFS_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockCoreProvider
func (_mock *MockCoreProvider) GetLogger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockCoreProvider_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockCoreProvider_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockCoreProvider_Expecter) GetLogger() *MockCoreProvider_GetLogger_Call {
	return &MockCoreProvider_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockCoreProvider_GetLogger_Call) Run(run func()) *MockCoreProvider_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCoreProvider_GetLogger_Call) Return(logger1 logger.Logger) *MockCoreProvider_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockCoreProvider_GetLogger_Call) RunAndReturn(run func() logger.Logger) *MockCoreProvider_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}
