// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/errorhandling"
	mock "github.com/stretchr/testify/mock"
)

// NewMockErrorHandlerProvider creates a new instance of MockErrorHandlerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockErrorHandlerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockErrorHandlerProvider {
	mock := &MockErrorHandlerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockErrorHandlerProvider is an autogenerated mock type for the ErrorHandlerProvider type
type MockErrorHandlerProvider struct {
	mock.Mock
}

type MockErrorHandlerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockErrorHandlerProvider) EXPECT() *MockErrorHandlerProvider_Expecter {
	return &MockErrorHandlerProvider_Expecter{mock: &_m.Mock}
}

// GetErrorHandler provides a mock function for the type MockErrorHandlerProvider
func (_mock *MockErrorHandlerProvider) GetErrorHandler() errorhandling.ErrorHandler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetErrorHandler")
	}

	var r0 errorhandling.ErrorHandler
	if returnFunc, ok := ret.Get(0).(func() errorhandling.ErrorHandler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errorhandling.ErrorHandler)
		}
	}
	return r0
}

// MockErrorHandlerProvider_GetErrorHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetErrorHandler'
type MockErrorHandlerProvider_GetErrorHandler_Call struct {
	*mock.Call
}

// GetErrorHandler is a helper method to define mock.On call
func (_e *MockErrorHandlerProvider_Expecter) GetErrorHandler() *MockErrorHandlerProvider_GetErrorHandler_Call {
	return &MockErrorHandlerProvider_GetErrorHandler_Call{Call: _e.mock.On("GetErrorHandler")}
}

func (_c *MockErrorHandlerProvider_GetErrorHandler_Call) Run(run func()) *MockErrorHandlerProvider_GetErrorHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockErrorHandlerProvider_GetErrorHandler_Call) Return(errorHandler errorhandling.ErrorHandler) *MockErrorHandlerProvider_GetErrorHandler_Call {
	_c.Call.Return(errorHandler)
	return _c
}

func (_c *MockErrorHandlerProvider_GetErrorHandler_Call) RunAndReturn(run func() errorhandling.ErrorHandler) *MockErrorHandlerProvider_GetErrorHandler_Call {
	_c.Call.Return(run)
	return _c
}
