// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerProvider creates a new instance of MockLoggerProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerProvider {
	mock := &MockLoggerProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerProvider is an autogenerated mock type for the LoggerProvider type
type MockLoggerProvider struct {
	mock.Mock
}

type MockLoggerProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerProvider) EXPECT() *MockLoggerProvider_Expecter {
	return &MockLoggerProvider_Expecter{mock: &_m.Mock}
}

// GetLogger provides a mock function for the type MockLoggerProvider
func (_mock *MockLoggerProvider) GetLogger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockLoggerProvider_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockLoggerProvider_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockLoggerProvider_Expecter) GetLogger() *MockLoggerProvider_GetLogger_Call {
	return &MockLoggerProvider_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockLoggerProvider_GetLogger_Call) Run(run func()) *MockLoggerProvider_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggerProvider_GetLogger_Call) Return(logger1 logger.Logger) *MockLoggerProvider_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLoggerProvider_GetLogger_Call) RunAndReturn(run func() logger.Logger) *MockLoggerProvider_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}
