// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/config"
	"github.com/phpboyscout/go-tool-base/pkg/logger"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggingConfigProvider creates a new instance of MockLoggingConfigProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggingConfigProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggingConfigProvider {
	mock := &MockLoggingConfigProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggingConfigProvider is an autogenerated mock type for the LoggingConfigProvider type
type MockLoggingConfigProvider struct {
	mock.Mock
}

type MockLoggingConfigProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggingConfigProvider) EXPECT() *MockLoggingConfigProvider_Expecter {
	return &MockLoggingConfigProvider_Expecter{mock: &_m.Mock}
}

// GetConfig provides a mock function for the type MockLoggingConfigProvider
func (_mock *MockLoggingConfigProvider) GetConfig() config.Containable {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.Containable
	if returnFunc, ok := ret.Get(0).(func() config.Containable); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Containable)
		}
	}
	return r0
}

// MockLoggingConfigProvider_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockLoggingConfigProvider_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockLoggingConfigProvider_Expecter) GetConfig() *MockLoggingConfigProvider_GetConfig_Call {
	return &MockLoggingConfigProvider_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockLoggingConfigProvider_GetConfig_Call) Run(run func()) *MockLoggingConfigProvider_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggingConfigProvider_GetConfig_Call) Return(containable config.Containable) *MockLoggingConfigProvider_GetConfig_Call {
	_c.Call.Return(containable)
	return _c
}

func (_c *MockLoggingConfigProvider_GetConfig_Call) RunAndReturn(run func() config.Containable) *MockLoggingConfigProvider_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockLoggingConfigProvider
func (_mock *MockLoggingConfigProvider) GetLogger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockLoggingConfigProvider_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockLoggingConfigProvider_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockLoggingConfigProvider_Expecter) GetLogger() *MockLoggingConfigProvider_GetLogger_Call {
	return &MockLoggingConfigProvider_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockLoggingConfigProvider_GetLogger_Call) Run(run func()) *MockLoggingConfigProvider_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoggingConfigProvider_GetLogger_Call) Return(logger1 logger.Logger) *MockLoggingConfigProvider_GetLogger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLoggingConfigProvider_GetLogger_Call) RunAndReturn(run func() logger.Logger) *MockLoggingConfigProvider_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}
