// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/props"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolMetadataProvider creates a new instance of MockToolMetadataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolMetadataProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolMetadataProvider {
	mock := &MockToolMetadataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolMetadataProvider is an autogenerated mock type for the ToolMetadataProvider type
type MockToolMetadataProvider struct {
	mock.Mock
}

type MockToolMetadataProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolMetadataProvider) EXPECT() *MockToolMetadataProvider_Expecter {
	return &MockToolMetadataProvider_Expecter{mock: &_m.Mock}
}

// GetTool provides a mock function for the type MockToolMetadataProvider
func (_mock *MockToolMetadataProvider) GetTool() props.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTool")
	}

	var r0 props.Tool
	if returnFunc, ok := ret.Get(0).(func() props.Tool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(props.Tool)
	}
	return r0
}

// MockToolMetadataProvider_GetTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTool'
type MockToolMetadataProvider_GetTool_Call struct {
	*mock.Call
}

// GetTool is a helper method to define mock.On call
func (_e *MockToolMetadataProvider_Expecter) GetTool() *MockToolMetadataProvider_GetTool_Call {
	return &MockToolMetadataProvider_GetTool_Call{Call: _e.mock.On("GetTool")}
}

func (_c *MockToolMetadataProvider_GetTool_Call) Run(run func()) *MockToolMetadataProvider_GetTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolMetadataProvider_GetTool_Call) Return(tool props.Tool) *MockToolMetadataProvider_GetTool_Call {
	_c.Call.Return(tool)
	return _c
}

func (_c *MockToolMetadataProvider_GetTool_Call) RunAndReturn(run func() props.Tool) *MockToolMetadataProvider_GetTool_Call {
	_c.Call.Return(run)
	return _c
}
