// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package props

import (
	"github.com/phpboyscout/go-tool-base/pkg/version"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionProvider creates a new instance of MockVersionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionProvider {
	mock := &MockVersionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionProvider is an autogenerated mock type for the VersionProvider type
type MockVersionProvider struct {
	mock.Mock
}

type MockVersionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionProvider) EXPECT() *MockVersionProvider_Expecter {
	return &MockVersionProvider_Expecter{mock: &_m.Mock}
}

// GetVersion provides a mock function for the type MockVersionProvider
func (_mock *MockVersionProvider) GetVersion() version.Version {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 version.Version
	if returnFunc, ok := ret.Get(0).(func() version.Version); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(version.Version)
		}
	}
	return r0
}

// MockVersionProvider_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockVersionProvider_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockVersionProvider_Expecter) GetVersion() *MockVersionProvider_GetVersion_Call {
	return &MockVersionProvider_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockVersionProvider_GetVersion_Call) Run(run func()) *MockVersionProvider_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersionProvider_GetVersion_Call) Return(version1 version.Version) *MockVersionProvider_GetVersion_Call {
	_c.Call.Return(version1)
	return _c
}

func (_c *MockVersionProvider_GetVersion_Call) RunAndReturn(run func() version.Version) *MockVersionProvider_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}
